// quedtion2.js - ENGLISH QUEST 応用編 (Ver 1.14 ヒント削除・正解判定修正版)
const masterQuestions = [
  // --- 語順整序・複雑な構文 (1-100) ---
  {q:"[asked / me / he / a question] 正しい順は？", choices:["He asked me a question.","He asked a question me.","Me he asked a question.","A question asked he me."], a:"He asked me a question.", j:"彼は私に質問をしました。"},
  {q:"[makes / he / happy / me] 彼は私を幸せにする", choices:["He makes me happy.","He happy makes me.","He makes happy me.","Me he makes happy."], a:"He makes me happy.", j:"「SVOC」の語順になるよう完成させてください。"},
  {q:"[found / I / the / easy / book] 私はその本が簡単だとわかった", choices:["I found the book easy.","I found easy the book.","I easy found the book.","The book found I easy."], a:"I found the book easy.", j:"「その本＝簡単」という関係になる語順です。"},
  {q:"[kept / she / me / waiting] 彼女は私を待たせ続けた", choices:["She kept me waiting.","She waiting kept me.","She kept waiting me.","Me she kept waiting."], a:"She kept me waiting.", j:"彼女は私をずっと待たせた状態にしました。"},
  {q:"I want ( ) to the party.", choices:["you to come","to you come","come to you","you come to"], a:"you to come", j:"「want + 人 + to do」の形です。"},
  {q:"He told me ( ) late.", choices:["not to be","to not be","be not to","not be to"], a:"not to be", j:"「tell + 人 + not to do」で「～しないように言う」となります。"},
  {q:"It is difficult ( ) English.", choices:["to speak","speak to","speaking","spoken"], a:"to speak", j:"It is ... (for 人) to ～ の構文です。"},
  {q:"I don't know ( ) to do.", choices:["what","how","where","when"], a:"what", j:"「何をすべきか」という疑問詞+不定詞です。"},
  {q:"( ) to the radio is fun.", choices:["Listening","Listen","Listened","To listening"], a:"Listening", j:"動名詞が主語になっています。"},
  {q:"She is ( ) a book.", choices:["reading","read","reads","to read"], a:"reading", j:"現在進行形です。"},
  {q:"The movie was ( ).", choices:["exciting","excited","excite","excites"], a:"exciting", j:"映画が「わくわくさせるもの」なのでing形を使います。"},
  {q:"I am ( ) in music.", choices:["interested","interesting","interest","interests"], a:"interested", j:"「（人が）興味がある」ときはed形を使います。"},
  {q:"( ) from the moon, the earth is blue.", choices:["Seen","Seeing","See","Saw"], a:"Seen", j:"「月から見られると」という分詞構文です。"},
  {q:"I have ( ) the book.", choices:["read","reading","reads","to read"], a:"read", j:"現在完了形（完了）です。"},
  {q:"He has ( ) to London.", choices:["gone","been","go","went"], a:"gone", j:"「行ってしまった（ここにはいない）」という意味です。"},
  {q:"I have ( ) to Tokyo twice.", choices:["been","gone","go","was"], a:"been", j:"「行ったことがある（経験）」という意味です。"},
  {q:"She ( ) been sick since Monday.", choices:["has","have","is","was"], a:"has", j:"現在完了の継続です。"},
  {q:"If it ( ) tomorrow, I will stay home.", choices:["rains","rain","will rain","rained"], a:"rains", j:"時や条件を表す副詞句では未来のことも現在形。"},
  {q:"I wish I ( ) rich.", choices:["were","am","was","be"], a:"were", j:"仮定法過去。現在の事実に反する願い。"},
  {q:"He speaks as if he ( ) everything.", choices:["knew","know","knows","known"], a:"knew", j:"「まるで～であるかのように」という仮定法。"},
  {q:"The girl ( ) is singing is my sister.", choices:["who","which","whom","whose"], a:"who", j:"主格の関係代名詞。"},
  {q:"This is the watch ( ) I lost.", choices:["which","who","whom","whose"], a:"which", j:"目的格の関係代名詞。"},
  {q:"I know the boy ( ) father is a doctor.", choices:["whose","who","which","whom"], a:"whose", j:"所有格の関係代名詞。"},
  {q:"That is ( ) he lives.", choices:["where","when","why","how"], a:"where", j:"「彼が住んでいる場所」を指す関係副詞。"},
  {q:"Tell me the reason ( ) you were late.", choices:["why","when","where","how"], a:"why", j:"理由を表す関係副詞。"},
  {q:"I like the way ( ) she talks.", choices:["how","when","where","why"], a:"how", j:"「～する方法、～するやり方」"},
  {q:"He is ( ) a kind boy.", choices:["such","so","very","too"], a:"such", j:"such + a + 形容詞 + 名詞 の語順。"},
  {q:"It was ( ) hot that I couldn't sleep.", choices:["so","such","very","too"], a:"so", j:"so + 形容詞 + that ... の構文。"},
  {q:"I was ( ) tired to walk.", choices:["too","so","very","such"], a:"too", j:"too ～ to ... 「あまりに～で...できない」。"},
  {q:"He is ( ) enough to drive a car.", choices:["old","older","oldest","very old"], a:"old", j:"形容詞 + enough to ... 「～するのに十分な...」。"},
  {q:"I ( ) play soccer when I was a child.", choices:["used to","am used to","get used to","use to"], a:"used to", j:"「かつかつて～したものだ（過去の習慣）」。"},
  {q:"I ( ) the door open.", choices:["left","kept","stayed","made"], a:"left", j:"「（ドアを）開けっ放しにする」。"},
  {q:"She ( ) her hair cut.", choices:["had","made","let","did"], a:"had", j:"「髪を切ってもらった（使役のhave）」。"},
  {q:"I saw him ( ) the street.", choices:["cross","crossed","to cross","crosses"], a:"cross", j:"知覚動詞 see + 目的語 + 原形不定詞。"},
  {q:"He seems ( ) ill.", choices:["to be","be","being","been"], a:"to be", j:"「～であるようだ」。"},
  {q:"I happened ( ) her in the mall.", choices:["to meet","meet","meeting","met"], a:"to meet", j:"「たまたま～する」。"},
  {q:"To ( ) the truth, I don't like him.", choices:["tell","say","speak","talk"], a:"tell", j:"慣用表現「実を言うと」。"},
  {q:"Strange to ( ), I saw a UFO.", choices:["say","tell","speak","talk"], a:"say", j:"慣用表現「奇妙なことに」。"},
  {q:"Needless to ( ), health is important.", choices:["say","tell","speak","talk"], a:"say", j:"慣用表現「言うまでもなく」。"},
  {q:"( ) speaking, I'm tired.", choices:["Generally","Strictly","Frankly","Roughly"], a:"Generally", j:"慣用表現「一般的に言って」。"},
  {q:"( ) speaking, he is wrong.", choices:["Strictly","Generally","Frankly","Roughly"], a:"Strictly", j:"慣用表現「厳密に言って」。"},
  {q:"( ) speaking, I don't like it.", choices:["Frankly","Generally","Strictly","Roughly"], a:"Frankly", j:"慣用表現「率直に言って」。"},
  {q:"( ) of her, she forgot my birthday.", choices:["Typical","Common","Natural","Usual"], a:"Typical", j:"「彼女らしい（彼女に特有な）ことに」。"},
  {q:"You had better ( ) there.", choices:["go","to go","going","went"], a:"go", j:"had better + 動詞の原形「～したほうがよい」。"},
  {q:"I would ( ) stay home than go out.", choices:["rather","better","sooner","prefer"], a:"rather", j:"would rather ～ than ... 「...よりむしろ～したい」。"},
  {q:"He ( ) well be angry.", choices:["may","can","must","will"], a:"may", j:"may well ～ 「～するのももっともだ」。"},
  {q:"You ( ) as well go now.", choices:["might","may","can","shall"], a:"might", j:"might as well ～ 「～したほうがましだ」。"},
  {q:"I ( ) not have said such a thing.", choices:["should","would","could","might"], a:"should", j:"should not have + 過去分詞「～すべきではなかったのに」。"},
  {q:"He ( ) have forgotten the date.", choices:["must","should","will","can"], a:"must", j:"must have + 過去分詞「～したに違いない」。"},
  {q:"It ( ) have been true.", choices:["can't","mustn't","shouldn't","won't"], a:"can't", j:"can't have + 過去分詞「～したはずがない」。"},
  {q:"Not ( ) what to say, I kept silent.", choices:["knowing","known","know","to know"], a:"knowing", j:"分詞構文の否定形。"},
  {q:"( ) from his accent, he is from Kyoto.", choices:["Judging","Judged","Judge","To judge"], a:"Judging", j:"「～から判断すると」。"},
  {q:"( ) weather permitting, we'll go.", choices:["Other","Some","The","Weather"], a:"Weather", j:"独立分詞構文「天気が許せば」。"},
  {q:"All things ( ), he is a good man.", choices:["considered","considering","consider","to consider"], a:"considered", j:"「すべてを考慮すると」。"},
  {q:"( ) that he is old, he is active.", choices:["Provided","Providing","Suppose","If"], a:"Provided", j:"「～という条件で、～を考慮すると」。"},
  {q:"He ( ) to be a doctor.", choices:["turned out","came out","went out","broke out"], a:"turned out", j:"「～だと判明した」。"},
  {q:"She ( ) up her mind to study hard.", choices:["made","took","gave","set"], a:"made", j:"make up one's mind「決心する」。"},
  {q:"I ( ) forward to seeing you.", choices:["look","watch","see","stare"], a:"look", j:"look forward to ～ing「～するのを楽しみに待つ」。"},
  {q:"He is ( ) of swimming.", choices:["fond","good","interested","keen"], a:"fond", j:"be fond of ～「～が好きだ」。"},
  {q:"She is ( ) in English.", choices:["fluent","good","clever","wise"], a:"fluent", j:"be fluent in ～「～が流暢だ」。"},
  {q:"I am ( ) of the news.", choices:["aware","know","sure","certain"], a:"aware", j:"be aware of ～「～に気づいている」。"},
  {q:"He is ( ) of success.", choices:["sure","know","aware","certain"], a:"sure", j:"be sure of ～「～を確信している」。"},
  {q:"The box is ( ) of books.", choices:["full","filled","empty","rich"], a:"full", j:"be full of ～「～でいっぱいだ」。"},
  {q:"She is ( ) for her beauty.", choices:["famous","known","popular","noted"], a:"famous", j:"be famous for ～「～で有名だ」。"},
  {q:"He is ( ) to everyone.", choices:["known","famous","popular","familiar"], a:"known", j:"be known to ～「～に知られている」。"},
  {q:"I am ( ) with this city.", choices:["familiar","known","aware","sure"], a:"familiar", j:"be familiar with ～「～に精通している」。"},
  {q:"She is ( ) with her job.", choices:["satisfied","happy","glad","pleased"], a:"satisfied", j:"be satisfied with ～「～に満足している」。"},
  {q:"I am ( ) for my mistake.", choices:["sorry","sad","glad","happy"], a:"sorry", j:"be sorry for ～「～を申し訳なく思う」。"},
  {q:"He is ( ) at tennis.", choices:["good","well","nice","fine"], a:"good", j:"be good at ～「～が得意だ」。"},
  {q:"She is ( ) on music.", choices:["keen","fond","good","interested"], a:"keen", j:"be keen on ～「～に熱中している」。"},
  {q:"I am ( ) about the exam.", choices:["anxious","worry","afraid","scared"], a:"anxious", j:"be anxious about ～「～を心配している」。"},
  {q:"He is ( ) from school today.", choices:["absent","present","late","away"], a:"absent", j:"be absent from ～「～を欠席する」。"},
  {q:"She is ( ) for the meeting.", choices:["late","absent","present","early"], a:"late", j:"be late for ～「～に遅れる」。"},
  {q:"I am ( ) of my son.", choices:["proud","glad","happy","fond"], a:"proud", j:"be proud of ～「～を誇りに思う」。"},
  {q:"He is ( ) of dogs.", choices:["afraid","scared","frightened","terrified"], a:"afraid", j:"be afraid of ～「～を怖がる」。"},
  {q:"She is ( ) of her results.", choices:["ashamed","sorry","sad","glad"], a:"ashamed", j:"be ashamed of ～「～を恥じている」。"},
  {q:"I am ( ) of the dark.", choices:["scared","afraid","frightened","terrified"], a:"scared", j:"be scared of ～「～が怖い」。"},
  {q:"He is ( ) for his age.", choices:["tall","short","old","young"], a:"tall", j:"「年の割には背が高い」。"},
  {q:"She is ( ) of money.", choices:["short","lack","low","small"], a:"short", j:"be short of ～「～が不足している」。"},
  {q:"I am ( ) to go.", choices:["ready","prepare","done","finished"], a:"ready", j:"be ready to ～「～する準備ができている」。"},
  {q:"He is ( ) to win.", choices:["likely","possible","probable","sure"], a:"likely", j:"be likely to ～「～しそうだ」。"},
  {q:"She is ( ) to be late.", choices:["apt","likely","sure","possible"], a:"apt", j:"be apt to ～「～しがちだ」。"},
  {q:"I am ( ) to help you.", choices:["willing","ready","glad","happy"], a:"willing", j:"be willing to ～「～するのをいとわない」。"},
  {q:"He is ( ) to help.", choices:["eager","willing","ready","glad"], a:"eager", j:"be eager to ～「～したがっている」。"},
  {q:"She is ( ) to meet him.", choices:["anxious","eager","willing","ready"], a:"anxious", j:"be anxious to ～「～したくてたまらない」。"},
  {q:"I am ( ) to hear that.", choices:["glad","happy","pleased","sorry"], a:"glad", j:"「それを聞いてうれしい」。"},
  {q:"He is ( ) to see the doctor.", choices:["afraid","scared","frightened","terrified"], a:"afraid", j:"「医者に会うのを怖がっている」。"},
  {q:"She is ( ) to learn.", choices:["quick","fast","slow","easy"], a:"quick", j:"be quick to ～「～するのが早い」。"},
  {q:"I am ( ) to understand.", choices:["slow","quick","fast","easy"], a:"slow", j:"be slow to ～「～するのが遅い」。"},
  {q:"It is ( ) to solve.", choices:["easy","hard","difficult","tough"], a:"easy", j:"「解くのが簡単だ」。"},
  {q:"It is ( ) to solve.", choices:["difficult","easy","hard","tough"], a:"difficult", j:"「解くのが難しい」。"},
  {q:"He is ( ) to come.", choices:["sure","likely","apt","possible"], a:"sure", j:"be sure to ～「必ず～する」。"},
  {q:"She is ( ) to succeed.", choices:["bound","sure","likely","apt"], a:"bound", j:"be bound to ～「きっと～するはずだ」。"},
  {q:"I am ( ) to you.", choices:["grateful","thankful","kind","nice"], a:"grateful", j:"be grateful to ～「～に感謝している」。"},
  {q:"He is ( ) to me.", choices:["kind","nice","grateful","gentle"], a:"kind", j:"be kind to ～「～に親切だ」。"},
  {q:"She is ( ) to children.", choices:["cruel","kind","nice","gentle"], a:"cruel", j:"be cruel to ～「～に残酷だ」。"},
  {q:"I am ( ) to his opinion.", choices:["opposed","against","contrary","different"], a:"opposed", j:"be opposed to ～「～に反対している」。"},
  {q:"He is ( ) to his brother.", choices:["different","opposed","contrary","similar"], a:"different", j:"be different from ～ (または to) 「～と違う」。"},
  {q:"She is ( ) to her mother.", choices:["similar","different","same","equal"], a:"similar", j:"be similar to ～「～と似ている」。"},
  {q:"I am ( ) of my success.", choices:["certain","sure","surely","certainly"], a:"certain", j:"be certain of ～「～を確信している」。"},

  // --- セクション2: 語彙・熟語 (101-300) ---
  {q:"「journey」の意味は？", choices:["旅","仕事","休憩","睡眠"], a:"旅", j:"意味を選択してください"},
  {q:"「joy」の意味は？", choices:["喜び","悲しみ","怒り","恐怖"], a:"喜び", j:"意味を選択してください"},
  {q:"「judge」の意味は？", choices:["判断する/裁判官","従う","遊ぶ","眠る"], a:"判断する/裁判官", j:"意味を選択してください"},
  {q:"「judicial」の意味は？", choices:["司法の","経済の","芸術の","個人的な"], a:"司法の", j:"意味を選択してください"},
  {q:"「junction」の意味は？", choices:["合流点","終点","中心","直線"], a:"合流点", j:"意味を選択してください"},
  {q:"「junior」の意味は？", choices:["年下の/下位の","年上の","同じの","古い"], a:"年下の/下位の", j:"意味を選択してください"},
  {q:"「jury」の意味は？", choices:["陪審員","被告","弁護士","警察"], a:"陪審員", j:"意味を選択してください"},
  {q:"「just」の意味は？", choices:["公正な/ただの","不当な","悪い","古い"], a:"公正な/ただの", j:"意味を選択してください"},
  {q:"「justice」の意味は？", choices:["正義","悪","嘘","犯罪"], a:"正義", j:"意味を選択してください"},
  {q:"「justify」の意味は？", choices:["正当化する","批判する","壊す","隠す"], a:"正当化する", j:"意味を選択してください"},
  {q:"「keen」の意味は？", choices:["鋭い/熱心な","鈍い","遅い","古い"], a:"鋭い/熱心な", j:"意味を選択してください"},
  {q:"「keep」の意味は？", choices:["保つ","捨てる","壊す","隠す"], a:"保つ", j:"意味を選択してください"},
  {q:"「key」の意味は？", choices:["鍵/重要な","壁","床","天井"], a:"鍵/重要な", j:"意味を選択してください"},
  {q:"「kind」の意味は？", choices:["親切な/種類","残酷な","悪い","古い"], a:"親切な/種類", j:"意味を選択してください"},
  {q:"「king」の意味は？", choices:["王","市民","兵士","農民"], a:"王", j:"意味を選択してください"},
  {q:"「knee」の意味は？", choices:["膝","肘","肩","指"], a:"膝", j:"意味を選択してください"},
  {q:"「knife」の意味は？", choices:["ナイフ","フォーク","スプーン","皿"], a:"ナイフ", j:"意味を選択してください"},
  {q:"「knock」の意味は？", choices:["叩く","押す","引く","回す"], a:"叩く", j:"意味を選択してください"},
  {q:"「know」の意味は？", choices:["知っている","忘れる","無視する","疑う"], a:"知っている", j:"意味を選択してください"},
  {q:"「knowledge」の意味は？", choices:["知識","無知","秘密","嘘"], a:"知識", j:"意味を選択してください"},
  {q:"「label」の意味は？", choices:["ラベル/札","箱","蓋","紐"], a:"ラベル/札", j:"意味を選択してください"},
  {q:"「labor」の意味は？", choices:["労働","遊び","休憩","睡眠"], a:"労働", j:"意味を選択してください"},
  {q:"「laboratory」の意味は？", choices:["研究所","体育館","図書館","教室"], a:"研究所", j:"意味を選択してください"},
  {q:"「lack」の意味は？", choices:["不足","過剰","十分","満足"], a:"不足", j:"意味を選択してください"},
  {q:"「lady」の意味は？", choices:["淑女/女性","男性","子供","老人"], a:"淑女/女性", j:"意味を選択してください"},
  {q:"「lake」の意味は？", choices:["湖","海","川","池"], a:"湖", j:"意味を選択してください"},
  {q:"「land」の意味は？", choices:["土地/着陸する","海","空","宇宙"], a:"土地/着陸する", j:"意味を選択してください"},
  {q:"「landscape」の意味は？", choices:["風景","人物","静物","肖像"], a:"風景", j:"意味を選択してください"},
  {q:"「language」の意味は？", choices:["言語","沈黙","筆記","外見"], a:"言語", j:"意味を選択してください"},
  {q:"「large」の意味は？", choices:["大きい","小さい","細い","短い"], a:"大きい", j:"意味を選択してください"},
  {q:"「last」の意味は？", choices:["最後の/続く","最初の","新しい","古い"], a:"最後の/続く", j:"意味を選択してください"},
  {q:"「late」の意味は？", choices:["遅い","早い","速い","鋭い"], a:"遅い", j:"意味を選択してください"},
  {q:"「laugh」の意味は？", choices:["笑う","泣く","怒る","叫ぶ"], a:"笑う", j:"意味を選択してください"},
  {q:"「launch」の意味は？", choices:["打ち上げる/開始する","終わる","止まる","隠す"], a:"打ち上げる/開始する", j:"意味を選択してください"},
  {q:"「law」の意味は？", choices:["法律","犯罪","警察","刑務所"], a:"法律", j:"意味を選択してください"},
  {q:"「lawyer」の意味は？", choices:["弁護士","被告","陪審員","裁判官"], a:"弁護士", j:"意味を選択してください"},
  {q:"「lay」の意味は？", choices:["横たえる/置く","立つ","歩く","走る"], a:"横たえる/置く", j:"意味を選択してください"},
  {q:"「lead」の意味は？", choices:["導く","従う","止まる","戻る"], a:"導く", j:"意味を選択してください"},
  {q:"「leader」の意味は？", choices:["指導者","部下","仲間","敵"], a:"指導者", j:"意味を選択してください"},
  {q:"「leaf」の意味は？", choices:["葉","茎","根","花"], a:"葉", j:"意味を選択してください"},
  {q:"「league」の意味は？", choices:["同盟/連盟","個人","孤独","対立"], a:"同盟/連盟", j:"意味を選択してください"},
  {q:"「learn」の意味は？", choices:["学ぶ","教える","忘れる","無視する"], a:"学ぶ", j:"意味を選択してください"},
  {q:"「least」の意味は？", choices:["最小の","最大の","多くの","少しの"], a:"最小の", j:"意味を選択してください"},
  {q:"「leave」の意味は？", choices:["去る/残す","来る","着く","留まる"], a:"去る/残す", j:"意味を選択してください"},
  {q:"「lecture」の意味は？", choices:["講義","遊び","休憩","睡眠"], a:"講義", j:"意味を選択してください"},
  {q:"「left」の意味は？", choices:["左/去った","右","上","下"], a:"左/去った", j:"意味を選択してください"},
  {q:"「leg」の意味は？", choices:["脚","腕","肩","首"], a:"脚", j:"意味を選択してください"},
  {q:"「legal」の意味は？", choices:["法律の/合法的な","違法の","個人的な","公式の"], a:"法律の/合法的な", j:"意味を選択してください"},
  {q:"「legend」の意味は？", choices:["伝説","事実","歴史","記録"], a:"伝説", j:"意味を選択してください"},
  {q:"「leisure」の意味は？", choices:["余暇","仕事","義務","責任"], a:"余暇", j:"意味を選択してください"},
  {q:"「lemon」の意味は？", choices:["レモン","リンゴ","バナナ","ブドウ"], a:"レモン", j:"意味を選択してください"},
  {q:"「lend」の意味は？", choices:["貸す","借りる","売る","買う"], a:"貸す", j:"意味を選択してください"},
  {q:"「length」の意味は？", choices:["長さ","重さ","高さ","幅"], a:"長さ", j:"意味を選択してください"},
  {q:"「lesson」の意味は？", choices:["レッスン/教訓","遊び","休憩","睡眠"], a:"レッスン/教訓", j:"意味を選択してください"},
  {q:"「let」の意味は？", choices:["～させる/許す","禁じる","止める","壊す"], a:"～させる/許す", j:"意味を選択してください"},
  {q:"「letter」の意味は？", choices:["手紙/文字","数字","絵","音"], a:"手紙/文字", j:"意味を選択してください"},
  {q:"「level」の意味は？", choices:["水準/平らな","坂","山","谷"], a:"水準/平らな", j:"意味を選択してください"},
  {q:"「liberal」の意味は？", choices:["自由主義の/寛大な","保守的な","厳しい","残酷な"], a:"自由主義の/寛大な", j:"意味を選択してください"},
  {q:"「library」の意味は？", choices:["図書館","体育館","研究所","教室"], a:"図書館", j:"意味を選択してください"},
  {q:"「license」の意味は？", choices:["免許/許可","禁止","違反","罰"], a:"免許/許可", j:"意味を選択してください"},
  {q:"「lie」の意味は？", choices:["横たわる/嘘","立つ","歩く","走る"], a:"横たわる/嘘", j:"意味を選択してください"},
  {q:"「life」の意味は？", choices:["命/生活","死","眠り","夢"], a:"命/生活", j:"意味を選択してください"},
  {q:"「lift」の意味は？", choices:["持ち上げる","下げる","押す","引く"], a:"持ち上げる", j:"意味を選択してください"},
  {q:"「light」の意味は？", choices:["光/軽い","闇/重い","音/硬い","味/柔らかい"], a:"光/軽い", j:"意味を選択してください"},
  {q:"「like」の意味は？", choices:["好き/～のような","嫌い","同じ","違う"], a:"好き/～のような", j:"意味を選択してください"},
  {q:"「limit」の意味は？", choices:["制限","自由","拡大","解放"], a:"制限", j:"意味を選択してください"},
  {q:"「line」の意味は？", choices:["線/列","点","円","角"], a:"線/列", j:"意味を選択してください"},
  {q:"「link」の意味は？", choices:["つながり","分離","独立","停止"], a:"つながり", j:"意味を選択してください"},
  {q:"「lip」の意味は？", choices:["唇","鼻","目","耳"], a:"唇", j:"意味を選択してください"},
  {q:"「list」の意味は？", choices:["リスト/目録","本","雑誌","新聞"], a:"リスト/目録", j:"意味を選択してください"},
  {q:"「listen」の意味は？", choices:["聴く","話す","見る","書く"], a:"聴く", j:"意味を選択してください"},
  {q:"「literary」の意味は？", choices:["文学の","科学の","数学の","歴史の"], a:"文学の", j:"意味を選択してください"},
  {q:"「literature」の意味は？", choices:["文学","科学","数学","歴史"], a:"文学", j:"意味を選択してください"},
  {q:"「little」の意味は？", choices:["小さい/ほとんど～ない","大きい","多い","長い"], a:"小さい/ほとんど～ない", j:"意味を選択してください"},
  {q:"「live」の意味は？", choices:["住む/生きる","死ぬ","眠る","夢見る"], a:"住む/生きる", j:"意味を選択してください"},
  {q:"「load」の意味は？", choices:["荷物/積む","空","軽い","捨てる"], a:"荷物/積む", j:"意味を選択してください"},
  {q:"「loan」の意味は？", choices:["ローン/貸付","寄付","収入","貯金"], a:"ローン/貸付", j:"意味を選択してください"},
  {q:"「local」の意味は？", choices:["地元の/各駅停車の","全国の","世界の","宇宙の"], a:"地元の/各駅停車の", j:"意味を選択してください"},
  {q:"「locate」の意味は？", choices:["位置づける","動かす","隠す","壊す"], a:"位置づける", j:"意味を選択してください"},
  {q:"「location」の意味は？", choices:["場所/位置","時間","理由","結果"], a:"場所/位置", j:"意味を選択してください"},
  {q:"「lock」の意味は？", choices:["鍵をかける","開ける","壊す","無くす"], a:"鍵をかける", j:"意味を選択してください"},
  {q:"「log」の意味は？", choices:["丸太/記録","板","枝","根"], a:"丸太/記録", j:"意味を選択してください"},
  {q:"「logic」の意味は？", choices:["論理","感情","想像","記憶"], a:"論理", j:"意味を選択してください"},
  {q:"「lonely」の意味は？", choices:["孤独な","賑やかな","幸せな","怒った"], a:"孤独な", j:"意味を選択してください"},
  {q:"「long」の意味は？", choices:["長い/切望する","短い","細い","狭い"], a:"長い/切望する", j:"意味を選択してください"},
  {q:"「look」の意味は？", choices:["見る/～に見える","聴く","話す","嗅ぐ"], a:"見る/～に見える", j:"意味を選択してください"},
  {q:"「loose」の意味は？", choices:["ゆるい/解き放たれた","きつい","硬い","重い"], a:"ゆるい/解き放たれた", j:"意味を選択してください"},
  {q:"「lord」の意味は？", choices:["主/君主","奴隷","市民","農民"], a:"主/君主", j:"意味を選択してください"},
  {q:"「lose」の意味は？", choices:["失う/負ける","得る/勝つ","探す/見つける","持つ/保つ"], a:"失う/負ける", j:"意味を選択してください"},
  {q:"「loss」の意味は？", choices:["損失","利益","成功","勝利"], a:"損失", j:"意味を選択してください"},
  {q:"「lost」の意味は？", choices:["道に迷った/失われた","見つかった","新しい","古い"], a:"道に迷った/失われた", j:"意味を選択してください"},
  {q:"「lot」の意味は？", choices:["たくさん/運命/くじ","少し","ゼロ","欠如"], a:"たくさん/運命/くじ", j:"意味を選択してください"},
  {q:"「loud」の意味は？", choices:["大声の","静かな","低い","鋭い"], a:"大声の", j:"意味を選択してください"},
  {q:"「love」の意味は？", choices:["愛","憎しみ","怒り","恐怖"], a:"愛", j:"意味を選択してください"},
  {q:"「low」の意味は？", choices:["低い","高い","長い","広い"], a:"低い", j:"意味を選択してください"},
  {q:"「loyal」の意味は？", choices:["忠実な","不実な","悪い","古い"], a:"忠実な", j:"意味を選択してください"},
  {q:"「luck」の意味は？", choices:["運","実力","努力","才能"], a:"運", j:"意味を選択してください"},
  {q:"「lucky」の意味は？", choices:["幸運な","不運な","悪い","古い"], a:"幸運な", j:"意味を選択してください"},
  {q:"「lunch」の意味は？", choices:["昼食","朝食","夕食","夜食"], a:"昼食", j:"意味を選択してください"},
  {q:"「lung」の意味は？", choices:["肺","心臓","胃","肝臓"], a:"肺", j:"意味を選択してください"},
  {q:"「machine」の意味は？", choices:["機械","道具","建物","乗り物"], a:"機械", j:"意味を選択してください"},
  {q:"「mad」の意味は？", choices:["怒った/熱狂した","悲しい","幸せな","驚いた"], a:"怒った/熱狂した", j:"意味を選択してください"},
  {q:"「magazine」の意味は？", choices:["雑誌","本","新聞","教科書"], a:"雑誌", j:"意味を選択してください"},
  {q:"「magic」の意味は？", choices:["魔法","科学","数学","歴史"], a:"魔法", j:"意味を選択してください"},
  {q:"「mail」の意味は？", choices:["郵便","電話","SNS","会話"], a:"郵便", j:"意味を選択してください"},
  {q:"「main」の意味は？", choices:["主要な","些細な","古い","新しい"], a:"主要な", j:"意味を選択してください"},
  {q:"「maintain」の意味は？", choices:["維持する","壊す","変える","捨てる"], a:"維持する", j:"意味を選択してください"},
  {q:"「major」の意味は？", choices:["主要な/専攻する","些細な","古い","新しい"], a:"主要な/専攻する", j:"意味を選択してください"},
  {q:"「majority」の意味は？", choices:["大多数","少数","半分","全部"], a:"大多数", j:"意味を選択してください"},
  {q:"「make」の意味は？", choices:["作る/～させる","壊す","捨てる","隠す"], a:"作る/～させる", j:"意味を選択してください"},
  {q:"「male」の意味は？", choices:["男性の","女性の","子供の","老人の"], a:"男性の", j:"意味を選択してください"},
  {q:"「mall」の意味は？", choices:["モール/商店街","学校","病院","公園"], a:"モール/商店街", j:"意味を選択してください"},
  {q:"「man」の意味は？", choices:["男/人間","女","子供","老人"], a:"男/人間", j:"意味を選択してください"},
  {q:"「manage」の意味は？", choices:["何とか～する/管理する","失敗する","止める","逃げる"], a:"何とか～する/管理する", j:"意味を選択してください"},
  {q:"「management」の意味は？", choices:["経営/管理","遊び","休憩","睡眠"], a:"経営/管理", j:"意味を選択してください"},
  {q:"「manager」の意味は？", choices:["管理者/監督","部下","仲間","敵"], a:"管理者/監督", j:"意味を選択してください"},
  {q:"「manner」の意味は？", choices:["方法/行儀","外見","性格","能力"], a:"方法/行儀", j:"意味を選択してください"},
  {q:"「many」の意味は？", choices:["多くの","少しの","ゼロの","一つの"], a:"多くの", j:"意味を選択してください"},
  {q:"「map」の意味は？", choices:["地図","絵","写真","図面"], a:"地図", j:"意味を選択してください"},
  {q:"「march」の意味は？", choices:["行進/3月","停止","後退","回転"], a:"行進/3月", j:"意味を選択してください"},
  {q:"「mark」の意味は？", choices:["印/点数","空白","沈黙","暗闇"], a:"印/点数", j:"意味を選択してください"},
  {q:"「market」の意味は？", choices:["市場","学校","病院","公園"], a:"市場", j:"意味を選択してください"},
  {q:"「marriage」の意味は？", choices:["結婚","離婚","誕生","葬式"], a:"結婚", j:"意味を選択してください"},
  {q:"「marry」の意味は？", choices:["結婚する","離婚する","生まれる","死ぬ"], a:"結婚する", j:"意味を選択してください"},
  {q:"「mass」の意味は？", choices:["集団/質量","個人","真空","虚無"], a:"集団/質量", j:"意味を選択してください"},
  {q:"「master」の意味は？", choices:["習得する/主人","見習う","忘れる","捨てる"], a:"習得する/主人", j:"意味を選択してください"},
  {q:"「match」の意味は？", choices:["試合/一致する","練習","失敗","対立"], a:"試合/一致する", j:"意味を選択してください"},
  {q:"「material」の意味は？", choices:["材料/資料","結果","理由","目的"], a:"材料/資料", j:"意味を選択してください"},
  {q:"「mathematics」の意味は？", choices:["数学","国語","英語","理科"], a:"数学", j:"意味を選択してください"},
  {q:"「matter」の意味は？", choices:["問題/事柄","解決","沈黙","虚無"], a:"問題/事柄", j:"意味を選択してください"},
  {q:"「maximum」の意味は？", choices:["最大","最小","平均","半分"], a:"最大", j:"意味を選択してください"},
  {q:"「may」の意味は？", choices:["～かもしれない/5月","～に違いない","～すべきだ","～しなければならない"], a:"～かもしれない/5月", j:"意味を選択してください"},
  {q:"「maybe」の意味は？", choices:["たぶん","絶対に","決して～ない","常に"], a:"たぶん", j:"意味を選択してください"},
  {q:"「mayor」の意味は？", choices:["市長","市民","大統領","議員"], a:"市長", j:"意味を選択してください"},
  {q:"「me」の意味は？", choices:["私を/に","私は","私の","私のもの"], a:"私を/に", j:"意味を選択してください"},
  {q:"「meal」の意味は？", choices:["食事","遊び","仕事","睡眠"], a:"食事", j:"意味を選択してください"},
  {q:"「mean」の意味は？", choices:["意味する/卑劣な","言う","聞く","書く"], a:"意味する/卑劣な", j:"意味を選択してください"},
  {q:"「meaning」の意味は？", choices:["意味","形","音","色"], a:"意味", j:"意味を選択してください"},
  {q:"「measure」の意味は？", choices:["測る/手段","壊す","捨てる","隠す"], a:"測る/手段", j:"意味を選択してください"},
  {q:"「measurement」の意味は？", choices:["測定","遊び","休憩","睡眠"], a:"測定", j:"意味を選択してください"},
  {q:"「meat」の意味は？", choices:["肉","魚","野菜","果物"], a:"肉", j:"意味を選択してください"},
  {q:"「media」の意味は？", choices:["媒体/マスコミ","個人","秘密","沈黙"], a:"媒体/マスコミ", j:"意味を選択してください"},
  {q:"「medical」の意味は？", choices:["医学の","法学の","工学の","芸術の"], a:"医学の", j:"意味を選択してください"},
  {q:"「medicine」の意味は？", choices:["薬/医学","毒","病気","健康"], a:"薬/医学", j:"意味を選択してください"},
  {q:"「medium」の意味は？", choices:["媒体/中間の","極端な","大きい","小さい"], a:"媒体/中間の", j:"意味を選択してください"},
  {q:"「meet」の意味は？", choices:["会う/満たす","別れる","去る","隠れる"], a:"会う/満たす", j:"意味を選択してください"},
  {q:"「meeting」の意味は？", choices:["会議","遊び","休憩","睡眠"], a:"会議", j:"意味を選択してください"},
  {q:"「member」の意味は？", choices:["一員","全体","部外者","敵"], a:"一員", j:"意味を選択してください"},
  {q:"「memory」の意味は？", choices:["記憶","忘却","想像","論理"], a:"記憶", j:"意味を選択してください"},
  {q:"「mental」の意味は？", choices:["精神の","肉体の","外部の","公式の"], a:"精神の", j:"意味を選択してください"},
  {q:"「mention」の意味は？", choices:["言及する","黙る","忘れる","隠す"], a:"言及する", j:"意味を選択してください"},
  {q:"「menu」の意味は？", choices:["献立表","本","雑誌","新聞"], a:"献立表", j:"意味を選択してください"},
  {q:"「merchant」の意味は？", choices:["商人","兵士","市民","農民"], a:"商人", j:"意味を選択してください"},
  {q:"「mercy」の意味は？", choices:["慈悲","残酷","怒り","恐怖"], a:"慈悲", j:"意味を選択してください"},
  {q:"「merely」の意味は？", choices:["単に","非常に","常に","決して～ない"], a:"単に", j:"意味を選択してください"},
  {q:"「message」の意味は？", choices:["伝言","沈黙","筆記","外見"], a:"伝言", j:"意味を選択してください"},
  {q:"「metal」の意味は？", choices:["金属","木材","石材","プラスチック"], a:"金属", j:"意味を選択してください"},
  {q:"「method」の意味は？", choices:["方法","偶然","混乱","停止"], a:"方法", j:"意味を選択してください"},
  {q:"「middle」の意味は？", choices:["中央","端","上","下"], a:"中央", j:"意味を選択してください"},
  {q:"「might」の意味は？", choices:["～かもしれない/力","～に違いない","～すべきだ","～しなければならない"], a:"～かもしれない/力", j:"意味を選択してください"},
  {q:"「mile」の意味は？", choices:["マイル(距離)","重さ","時間","速度"], a:"マイル(距離)", j:"意味を選択してください"},
  {q:"「military」の意味は？", choices:["軍隊の","民間の","平和の","自由の"], a:"軍隊の", j:"意味を選択してください"},
  {q:"「milk」の意味は？", choices:["牛乳","水","お茶","ジュース"], a:"牛乳", j:"意味を選択してください"},
  {q:"「million」の意味は？", choices:["百万","十万","千万","一億"], a:"百万", j:"意味を選択してください"},
  {q:"「mind」の意味は？", choices:["心/気にする","体","物","お金"], a:"心/気にする", j:"意味を選択してください"},
  {q:"「mine」の意味は？", choices:["私のもの/鉱山","私の","私を","私は"], a:"私のもの/鉱山", j:"意味を選択してください"},
  {q:"「mineral」の意味は？", choices:["鉱物","植物","動物","人間"], a:"鉱物", j:"意味を選択してください"},
  {q:"「minimum」の意味は？", choices:["最小","最大","平均","半分"], a:"最小", j:"意味を選択してください"},
  {q:"「minister」の意味は？", choices:["大臣/牧師","王","兵士","農民"], a:"大臣/牧師", j:"意味を選択してください"},
  {q:"「minor」の意味は？", choices:["些細な/未成年者","主要な","古い","新しい"], a:"些細な/未成年者", j:"意味を選択してください"},
  {q:"「minority」の意味は？", choices:["少数派","多数派","半分","全部"], a:"少数派", j:"意味を選択してください"},
  {q:"「minute」の意味は？", choices:["分/微細な","時間","秒","日"], a:"分/微細な", j:"意味を選択してください"},
  {q:"「mirror」の意味は？", choices:["鏡","窓","壁","床"], a:"鏡", j:"意味を選択してください"},
  {q:"「miss」の意味は？", choices:["逃す/恋しく思う","捕まえる","会う","忘れる"], a:"逃す/恋しく思う", j:"意味を選択してください"},
  {q:"「mission」の意味は？", choices:["使命/任務","遊び","休憩","睡眠"], a:"使命/任務", j:"意味を選択してください"},
  {q:"「mistake」の意味は？", choices:["間違い","正解","成功","勝利"], a:"間違い", j:"意味を選択してください"},
  {q:"「mix」の意味は？", choices:["混ぜる","分ける","壊す","隠す"], a:"混ぜる", j:"意味を選択してください"},
  {q:"「mixture」の意味は？", choices:["混合物","純粋","単一","虚無"], a:"混合物", j:"意味を選択してください"},
  {q:"「model」の意味は？", choices:["模型/手本","実物","嘘","過去"], a:"模型/手本", j:"意味を選択してください"},
  {q:"「moderate」の意味は？", choices:["適度な","過激な","極端な","激しい"], a:"適度な", j:"意味を選択してください"},
  {q:"「modern」の意味は？", choices:["現代の","古代の","伝統的な","古い"], a:"現代の", j:"意味を選択してください"},
  {q:"「modest」の意味は？", choices:["謙虚な","傲慢な","派手な","うるさい"], a:"謙虚な", j:"意味を選択してください"},
  {q:"「moment」の意味は？", choices:["瞬間","永遠","過去","未来"], a:"瞬間", j:"意味を選択してください"},
  {q:"「money」の意味は？", choices:["お金","時間","心","体"], a:"お金", j:"意味を選択してください"},
  {q:"「monitor」の意味は？", choices:["監視する/画面","無視する","壊す","隠す"], a:"監視する/画面", j:"意味を選択してください"},
  {q:"「monkey」の意味は？", choices:["猿","犬","猫","鳥"], a:"猿", j:"意味を選択してください"},
  {q:"「month」の意味は？", choices:["月","年","週","日"], a:"月", j:"意味を選択してください"},
  {q:"「mood」の意味は？", choices:["気分","知能","外見","能力"], a:"気分", j:"意味を選択してください"},
  {q:"「moon」の意味は？", choices:["月","太陽","星","地球"], a:"月", j:"意味を選択してください"},
  {q:"「moral」の意味は？", choices:["道徳的な","不道徳な","悪い","古い"], a:"道徳的な", j:"意味を選択してください"},
  {q:"「more」の意味は？", choices:["より多くの","より少ない","同じ","ゼロ"], a:"より多くの", j:"意味を選択してください"},
  {q:"「morning」の意味は？", choices:["朝","昼","夕方","夜"], a:"朝", j:"意味を選択してください"},
  {q:"「most」の意味は？", choices:["最も多い/大部分","最も少ない","少し","ゼロ"], a:"最も多い/大部分", j:"意味を選択してください"},
  {q:"「mother」の意味は？", choices:["母","父","息子","娘"], a:"母", j:"意味を選択してください"},
  {q:"「motion」の意味は？", choices:["動き","静止","沈黙","暗闇"], a:"動き", j:"意味を選択してください"},
  {q:"「motivation」の意味は？", choices:["動機づけ","無気力","停止","虚無"], a:"動機づけ", j:"意味を選択してください"},
  {q:"「motor」の意味は？", choices:["原動機","車体","タイヤ","燃料"], a:"原動機", j:"意味を選択してください"},
  {q:"「mountain」の意味は？", choices:["山","海","川","谷"], a:"山", j:"意味を選択してください"},
  {q:"「mouse」の意味は？", choices:["鼠","犬","猫","鳥"], a:"鼠", j:"意味を選択してください"},
  {q:"「mouth」の意味は？", choices:["口","鼻","目","耳"], a:"口", j:"意味を選択してください"},
  {q:"「move」の意味は？", choices:["動く/感動させる","止まる","座る","眠る"], a:"動く/感動させる", j:"意味を選択してください"},
  {q:"「movement」の意味は？", choices:["動き/運動","静止","沈黙","暗闇"], a:"動き/運動", j:"意味を選択してください"},
  {q:"「movie」の意味は？", choices:["映画","本","雑誌","新聞"], a:"映画", j:"意味を選択してください"},
  {q:"「much」の意味は？", choices:["多くの/とても","少ない","ゼロ","一つの"], a:"多くの/とても", j:"意味を選択してください"},
  {q:"「murder」の意味は？", choices:["殺人","窃盗","詐欺","平和"], a:"殺人", j:"意味を選択してください"},
  {q:"「muscle」の意味は？", choices:["筋肉","骨","皮膚","血管"], a:"筋肉", j:"意味を選択してください"},
  {q:"「museum」の意味は？", choices:["博物館/美術館","学校","病院","公園"], a:"博物館/美術館", j:"意味を選択してください"},
  {q:"「music」の意味は？", choices:["音楽","美術","体育","数学"], a:"音楽", j:"意味を選択してください"},
  {q:"「must」の意味は？", choices:["～しなければならない","～かもしれない","～してもよい","～だろう"], a:"～しなければならない", j:"意味を選択してください"},
  {q:"「mutual」の意味は？", choices:["相互の","一方的な","独立した","共通の"], a:"相互の", j:"意味を選択してください"},
  {q:"「my」の意味は？", choices:["私の","私は","私を","私のもの"], a:"私の", j:"意味を選択してください"},
  {q:"「myself」の意味は？", choices:["私自身","あなた自身","彼自身","彼女自身"], a:"私自身", j:"意味を選択してください"},
  {q:"「mystery」の意味は？", choices:["謎","事実","公表","理解"], a:"謎", j:"意味を選択してください"},
  {q:"「nail」の意味は？", choices:["爪/釘","指","髪","肌"], a:"爪/釘", j:"意味を選択してください"},
  {q:"「naked」の意味は？", choices:["裸の","服を着た","隠れた","公式の"], a:"裸の", j:"意味を選択してください"},
  {q:"「name」の意味は？", choices:["名前","外見","性格","能力"], a:"名前", j:"意味を選択してください"},
  {q:"「narrow」の意味は？", choices:["狭い","広い","高い","低い"], a:"狭い", j:"意味を選択してください"},
  {q:"「nation」の意味は？", choices:["国家","都市","村","家庭"], a:"国家", j:"意味を選択してください"},
  {q:"「national」の意味は？", choices:["国家の/国民の","個人の","地方の","世界の"], a:"国家の/国民の", j:"意味を選択してください"},
  {q:"「native」の意味は？", choices:["出身の/母国の","外国の","遠い","新しい"], a:"出身の/母国の", j:"意味を選択してください"},
  {q:"「natural」の意味は？", choices:["自然の/当然の","人工的な","不自然な","悪い"], a:"自然の/当然の", j:"意味を選択してください"},
  {q:"「nature」の意味は？", choices:["自然/性質","都市","科学","技術"], a:"自然/性質", j:"意味を選択してください"},
  {q:"「near」の意味は？", choices:["近い","遠い","広い","狭い"], a:"近い", j:"意味を選択してください"},
  {q:"「nearly」の意味は？", choices:["ほとんど","決して～ない","常に","たぶん"], a:"ほとんど", j:"意味を選択してください"},
  {q:"「neat」の意味は？", choices:["きちんとした","汚い","古い","新しい"], a:"きちんとした", j:"意味を選択してください"},
  {q:"「necessary」の意味は？", choices:["必要な","不必要な","便利な","快適な"], a:"必要な", j:"意味を選択してください"},
  {q:"「neck」の意味は？", choices:["首","肩","腕","脚"], a:"首", j:"意味を選択してください"},
  {q:"「need」の意味は？", choices:["必要がある","不必要だ","止める","変える"], a:"必要がある", j:"意味を選択してください"},
  {q:"「negative」の意味は？", choices:["否定的な","肯定的な","良い","新しい"], a:"否定的な", j:"意味を選択してください"},
  {q:"「neglect」の意味は？", choices:["怠る/無視する","大切にする","守る","育てる"], a:"怠る/無視する", j:"意味を選択してください"},
  {q:"「negotiate」の意味は？", choices:["交渉する","戦う","逃げる","隠れる"], a:"交渉する", j:"意味を選択してください"},
  {q:"「neighbor」の意味は？", choices:["隣人","他人","敵","指導者"], a:"隣人", j:"意味を選択してください"},
  {q:"「neither」の意味は？", choices:["どちらも～ない","どちらか一方","両方","全部"], a:"どちらも～ない", j:"意味を選択してください"},
  {q:"「nerve」の意味は？", choices:["神経/勇気","筋肉","骨","皮膚"], a:"神経/勇気", j:"意味を選択してください"},
  {q:"「nervous」の意味は？", choices:["緊張して/神経質な","落ち着いた","幸せな","怒った"], a:"緊張して/神経質な", j:"意味を選択してください"},
  {q:"「nest」の意味は？", choices:["巣","家","ビル","穴"], a:"巣", j:"意味を選択してください"},
  {q:"「net」の意味は？", choices:["網/正味の","紐","糸","布"], a:"網/正味の", j:"意味を選択してください"},
  {q:"「network」の意味は？", choices:["ネットワーク","孤立","停止","混乱"], a:"ネットワーク", j:"意味を選択してください"},
  {q:"「never」の意味は？", choices:["決して～ない","常に","時々","一度だけ"], a:"決して～ない", j:"意味を選択してください"},
  {q:"「new」の意味は？", choices:["新しい","古い","伝統的な","中古の"], a:"新しい", j:"意味を選択してください"},
  {q:"「news」の意味は？", choices:["知らせ/ニュース","沈黙","過去","秘密"], a:"知らせ/ニュース", j:"意味を選択してください"},
  {q:"「next」の意味は？", choices:["次の","前の","最後の","最初の"], a:"次の", j:"意味を選択してください"},
  {q:"「nice」の意味は？", choices:["良い/親切な","悪い","古い","新しい"], a:"良い/親切な", j:"意味を選択してください"},
  {q:"「night」の意味は？", choices:["夜","昼","朝","夕方"], a:"夜", j:"意味を選択してください"},
  {q:"「nine」の意味は？", choices:["9","6","7","8"], a:"9", j:"意味を選択してください"},
  {q:"「no」の意味は？", choices:["いいえ/一つの～もない","はい","少し","たくさん"], a:"いいえ/一つの～もない", j:"意味を選択してください"},
  {q:"「noble」の意味は？", choices:["高貴な","卑しい","悪い","古い"], a:"高貴な", j:"意味を選択してください"},
  {q:"「nobody」の意味は？", choices:["誰も～ない","誰か","みんな","彼ら"], a:"誰も～ない", j:"意味を選択してください"},
  {q:"「noise」の意味は？", choices:["騒音","静寂","音楽","声"], a:"騒音", j:"意味を選択してください"},
  {q:"「none」の意味は？", choices:["何も～ない","いくつか","全部","少し"], a:"何も～ない", j:"意味を選択してください"},
  {q:"「noon」の意味は？", choices:["正午","午前","午後","夜"], a:"正午", j:"意味を選択してください"},
  {q:"「nor」の意味は？", choices:["～もまた～ない","～もまた～である","しかし","または"], a:"～もまた～ない", j:"意味を選択してください"},
  {q:"「normal」の意味は？", choices:["普通の","異常な","極端な","激しい"], a:"普通の", j:"意味を選択してください"},
  {q:"「north」の意味は？", choices:["北","南","東","西"], a:"北", j:"意味を選択してください"},
  {q:"「nose」の意味は？", choices:["鼻","目","耳","口"], a:"鼻", j:"意味を選択してください"},
  {q:"「not」の意味は？", choices:["～ない","～である","～すぎる","～とても"], a:"～ない", j:"意味を選択してください"},
  {q:"「note」の意味は？", choices:["メモ/注意する","忘れる","無視する","壊す"], a:"メモ/注意する", j:"意味を選択してください"},
  {q:"「nothing」の意味は？", choices:["何も～ない","何か","全て","少し"], a:"何も～ない", j:"意味を選択してください"},
  {q:"「notice」の意味は？", choices:["気づく/掲示","見逃す","忘れる","隠す"], a:"気づく/掲示", j:"意味を選択してください"},
  {q:"「notion」の意味は？", choices:["概念/考え","事実","沈黙","虚無"], a:"概念/考え", j:"意味を選択してください"},
  {q:"「novel」の意味は？", choices:["小説/斬新な","本","雑誌","新聞"], a:"小説/斬新な", j:"意味を選択してください"},
  {q:"「now」の意味は？", choices:["今","過去","未来","後で"], a:"今", j:"意味を選択してください"},
  {q:"「nuclear」の意味は？", choices:["原子力の/核の","火力の","水力の","風力の"], a:"原子力の/核の", j:"意味を選択してください"},
  {q:"「number」の意味は？", choices:["数","文字","形","色"], a:"数", j:"意味を選択してください"},
  {q:"「numerous」の意味は？", choices:["多数の","少数の","ゼロの","一つの"], a:"多数の", j:"意味を選択してください"},
  {q:"「nurse」の意味は？", choices:["看護師","医者","患者","薬剤師"], a:"看護師", j:"意味を選択してください"},
  {q:"「nut」の意味は？", choices:["木の実","果物","野菜","肉"], a:"木の実", j:"意味を選択してください"},
  {q:"「object」の意味は？", choices:["物体/反対する","同意する","守る","壊す"], a:"物体/反対する", j:"意味を選択してください"},
  {q:"「objective」の意味は？", choices:["客観的な/目標","主観的な","感情的な","個人的な"], a:"客観的な/目標", j:"意味を選択してください"},
  {q:"「obligation」の意味は？", choices:["義務","権利","自由","余暇"], a:"義務", j:"意味を選択してください"},
  {q:"「observation」の意味は？", choices:["観察","遊び","休憩","睡眠"], a:"観察", j:"意味を選択してください"},
  {q:"「observe」の意味は？", choices:["観察する/守る","無視する","忘れる","壊す"], a:"観察する/守る", j:"意味を選択してください"},
  {q:"「obtain」の意味は？", choices:["得る","失う","捨てる","隠す"], a:"得る", j:"意味を選択してください"},
  {q:"「obvious」の意味は？", choices:["明白な","曖昧な","複雑な","難しい"], a:"明白な", j:"意味を選択してください"},
  {q:"「occasion」の意味は？", choices:["機会/行事","時間","理由","結果"], a:"機会/行事", j:"意味を選択してください"},
  {q:"「occupation」の意味は？", choices:["職業/占領","遊び","休憩","睡眠"], a:"職業/占領", j:"意味を選択してください"},
  {q:"「occupy」の意味は？", choices:["占める/占領する","去る","空ける","離れる"], a:"占める/占領する", j:"意味を選択してください"},
  {q:"「occur」の意味は？", choices:["起こる/心に浮かぶ","消える","終わる","止まる"], a:"起こる/心に浮かぶ", j:"意味を選択してください"},
  {q:"「ocean」の意味は？", choices:["海洋","湖","川","池"], a:"海洋", j:"意味を選択してください"},
  {q:"「off」の意味は？", choices:["離れて/休みで","着いて","中で","上で"], a:"離れて/休みで", j:"意味を選択してください"},
  {q:"「offend」の意味は？", choices:["気分を害する","喜ばせる","助ける","守る"], a:"気分を害する", j:"意味を選択してください"},
  {q:"「offer」の意味は？", choices:["提供する","断る","奪う","隠す"], a:"提供する", j:"意味を選択してください"},
  {q:"「office」の意味は？", choices:["事務所","学校","病院","公園"], a:"事務所", j:"意味を選択してください"},
  {q:"「officer」の意味は？", choices:["役人/警官","市民","泥棒","農民"], a:"役人/警官", j:"意味を選択してください"},
  {q:"「official」の意味は？", choices:["公式の","非公式の","個人の","秘密の"], a:"公式の", j:"意味を選択してください"},
  {q:"「often」の意味は？", choices:["しばしば","決して～ない","時々","一度だけ"], a:"しばしば", j:"意味を選択してください"},
  {q:"「oil」の意味は？", choices:["油","水","土","空気"], a:"油", j:"意味を選択してください"},
  {q:"「old」の意味は？", choices:["古い","新しい","斬新な","現代的な"], a:"古い", j:"意味を選択してください"},
  {q:"「on」の意味は？", choices:["上で/～について","下で","中で","外で"], a:"上で/～について", j:"意味を選択してください"},
  {q:"「once」の意味は？", choices:["一度/かつて","二度","常に","決して～ない"], a:"一度/かつて", j:"意味を選択してください"},
  {q:"「one」の意味は？", choices:["1/一つ","2","3","4"], a:"1/一つ", j:"意味を選択してください"},
  {q:"「only」の意味は？", choices:["～だけ/唯一の","たくさん","いくつか","全部"], a:"～だけ/唯一の", j:"意味を選択してください"},
  {q:"「open」の意味は？", choices:["開ける","閉める","壊す","隠す"], a:"開ける", j:"意味を選択してください"},
  {q:"「operate」の意味は？", choices:["操作する/手術する","止める","壊す","休む"], a:"操作する/手術する", j:"意味を選択してください"},
  {q:"「opinion」の意味は？", choices:["意見","事実","沈黙","虚無"], a:"意見", j:"意味を選択してください"},
  {q:"「opportunity」の意味は？", choices:["機会","危機","困難","失敗"], a:"機会", j:"意味を選択してください"},
  {q:"「oppose」の意味は？", choices:["反対する","賛成する","守る","助ける"], a:"反対する", j:"意味を選択してください"},
  {q:"「opposite」の意味は？", choices:["反対の","同じの","似ている","共通の"], a:"反対の", j:"意味を選択してください"},
  {q:"「option」の意味は？", choices:["選択肢","強制","義務","責任"], a:"選択肢", j:"意味を選択してください"},
  {q:"「or」の意味は？", choices:["または/さもなければ","そして","しかし","だから"], a:"または/さもなければ", j:"意味を選択してください"},
  {q:"「orange」の意味は？", choices:["オレンジ","リンゴ","バナナ","ブドウ"], a:"オレンジ", j:"意味を選択してください"},
  {q:"「order」の意味は？", choices:["注文/順序/命令","混乱","停止","拒否"], a:"注文/順序/命令", j:"意味を選択してください"},
  {q:"「ordinary」の意味は？", choices:["普通の","特別な","異常な","激しい"], a:"普通の", j:"意味を選択してください"},
  {q:"「organization」の意味は？", choices:["組織","個人","孤独","混乱"], a:"組織", j:"意味を選択してください"},
  {q:"「organize」の意味は？", choices:["組織する/準備する","壊す","捨てる","忘れる"], a:"組織する/準備する", j:"意味を選択してください"},
  {q:"「origin」の意味は？", choices:["起源","結果","未来","終わり"], a:"起源", j:"意味を選択してください"},
  {q:"「original」の意味は？", choices:["独創的な/元の","真似した","新しい","古い"], a:"独創的な/元の", j:"意味を選択してください"},
  {q:"「other」の意味は？", choices:["他の","同じの","自分の","全ての"], a:"他の", j:"意味を選択してください"},
  {q:"「otherwise」の意味は？", choices:["さもなければ","その上","しかし","だから"], a:"さもなければ", j:"意味を選択してください"},
  {q:"「ought to」の意味は？", choices:["～すべきだ","～かもしれない","～してもよい","～だろう"], a:"～すべきだ", j:"意味を選択してください"},
  {q:"「our」の意味は？", choices:["私たちの","私たちは","私たちを","私たちのもの"], a:"私たちの", j:"意味を選択してください"},
  {q:"「out」の意味は？", choices:["外へ","中へ","上で","下で"], a:"外へ", j:"意味を選択してください"},
  {q:"「outcome」の意味は？", choices:["結果","原因","理由","過程"], a:"結果", j:"意味を選択してください"},
  {q:"「output」の意味は？", choices:["出力","入力","貯蔵","消費"], a:"出力", j:"意味を選択してください"},
  {q:"「outside」の意味は？", choices:["外側","内側","上部","底部"], a:"外側", j:"意味を選択してください"},
  {q:"「outstanding」の意味は？", choices:["目立った/未解決の","普通の","些細な","古い"], a:"目立った/未解決の", j:"意味を選択してください"},
  {q:"「over」の意味は？", choices:["～の上に/終わって","～の下に","～の中で","～の前に"], a:"～の上に/終わって", j:"意味を選択してください"},
  {q:"「overall」の意味は？", choices:["全般的な","部分的な","些細な","個人的な"], a:"全般的な", j:"意味を選択してください"},
  {q:"「overcome」の意味は？", choices:["克服する","負ける","逃げる","諦める"], a:"克服する", j:"意味を選択してください"},
  {q:"「overlook」の意味は？", choices:["見落とす/見渡す","注意深く見る","忘れる","隠す"], a:"見落とす/見渡す", j:"意味を選択してください"},
  {q:"「owe」の意味は？", choices:["借りがある","貸している","持っている","失う"], a:"借りがある", j:"意味を選択してください"},
  {q:"「own」の意味は？", choices:["所有する/自身の","借りる","貸す","捨てる"], a:"所有する/自身の", j:"意味を選択してください"},
  {q:"「owner」の意味は？", choices:["所有者","従業員","部外者","敵"], a:"所有者", j:"意味を選択してください"},
  {q:"「improve」の意味は？", choices:["改善する","証明する","含む","示す"], a:"改善する", j:"意味を選択してください"},
  {q:"「individual」の意味は？", choices:["個人の","集団の","公式の","複雑な"], a:"個人の", j:"意味を選択してください"},
  {q:"「attitude」の意味は？", choices:["態度","高度","能力","知能"], a:"態度", j:"意味を選択してください"},
  {q:"「increase」の意味は？", choices:["増加する","減少する","維持する","破壊する"], a:"増加する", j:"意味を選択してください"},
  {q:"「benefit」の意味は？", choices:["利益・恩恵","損害","努力","恐怖"], a:"利益・恩恵", j:"意味を選択してください"},
  {q:"「pollute」の意味は？", choices:["汚染する","保護する","生産する","消費する"], a:"汚染する", j:"意味を選択してください"},
  {q:"「necessary」の意味は？", choices:["必要な","不可能な","便利な","快適な"], a:"必要な", j:"意味を選択してください"},
  {q:"「experience」の意味は？", choices:["経験","実験","期待","表現"], a:"経験", j:"意味を選択してください"},
  {q:"「available」の意味は？", choices:["利用可能な","高価な","貴重な","空っぽの"], a:"利用可能な", j:"意味を選択してください"},
  {q:"「advantage」の意味は？", choices:["利点","欠点","勇気","沈黙"], a:"利点", j:"意味を選択してください"},
  {q:"「essential」の意味は？", choices:["不可欠な","一時的な","伝統的な","個人的な"], a:"不可欠な", j:"意味を選択してください"},
  {q:"「government」の意味は？", choices:["政府","企業","学校","軍隊"], a:"政府", j:"意味を選択してください"},
  {q:"「society」の意味は？", choices:["社会","個人","家族","自然"], a:"社会", j:"意味を選択してください"}
];
