// quedtion2.js - ENGLISH QUEST 応用編 (Ver 1.13 完全版)
const masterQuestions = [
  // --- 語順整序・複雑な構文 (1-100) ---
  {q:"[asked / me / he / a question] 正しい順は？", choices:["He asked me a question.","He asked a question me.","Me he asked a question.","A question asked he me."], a:"He asked me a question.", j:"彼は私に質問をしました。"},
  {q:"[makes / he / happy / me] 彼は私を幸せにする", choices:["He makes me happy.","He happy makes me.","He makes happy me.","Me he makes happy."], a:"He makes me happy.", j:"「SVOC」の語順になるよう完成させてください。"},
  {q:"[found / I / the / easy / book] 私はその本が簡単だとわかった", choices:["I found the book easy.","I found easy the book.","I easy found the book.","The book found I easy."], a:"I found the book easy.", j:"「その本＝簡単」という関係になる語順です。"},
  {q:"[kept / she / me / waiting] 彼女は私を待たせ続けた", choices:["She kept me waiting.","She waiting kept me.","She kept waiting me.","Me she kept waiting."], a:"She kept me waiting.", j:"彼女は私をずっと待たせた状態にしました。"},
  {q:"I want ( ) to the party. [you / to / come]", choices:["you to come","to you come","come to you","you come to"], a:"you to come", j:"あなたにパーティーに来てほしいです。"},
  {q:"He told me ( ) late. [not / be / to]", choices:["not to be","to not be","be not to","not be to"], a:"not to be", j:"彼は私に遅れないように言いました。"},
  {q:"It is important ( ) English. [to / learn]", choices:["to learn","learn to","to learning","learning to"], a:"to learn", j:"英語を学ぶことは重要です。"},
  {q:"He is ( ) to solve the problem. [enough / wise]", choices:["wise enough","enough wise","wisely enough","enough wisely"], a:"wise enough", j:"彼はその問題を解決できるほど賢い。"},
  {q:"I don't know ( ) next. [what / do / to]", choices:["what to do","to what do","do what to","to do what"], a:"what to do", j:"次に何をすべきか分かりません。"},
  {q:"She ( ) her homework by then. [finished / will / have]", choices:["will have finished","have finished will","finished will have","will finished have"], a:"will have finished", j:"彼女はその時までに宿題を終えているでしょう。"},
  {q:"If I ( ) rich, I could buy the car. [were]", choices:["were","am","was","been"], a:"were", j:"もし私がお金持ちなら、その車を買えるのに。"},
  {q:"( ) he was tired, he kept working.", choices:["Though","Despite","But","However"], a:"Though", j:"彼は疲れていたけれど、働き続けました。"},
  {q:"I had my hair ( ) yesterday.", choices:["cut","cutting","to cut","cuts"], a:"cut", j:"私は昨日、髪を切ってもらいました。"},
  {q:"She is used ( ) up early.", choices:["to getting","to get","get","getting"], a:"to getting", j:"彼女は早起きすることに慣れています。"},
  {q:"No other river is ( ) the Nile.", choices:["as long as","longer than","longest of","so long as"], a:"as long as", j:"ナイル川ほど長い川は他にありません。"},
  {q:"It ( ) three years since he died.", choices:["is","was","has been","had been"], a:"has been", j:"彼が亡くなってから3年になります。"},
  {q:"He is the last person ( ) a lie.", choices:["to tell","telling","tells","tell"], a:"to tell", j:"彼は決して嘘をつくような人ではありません。"},
  {q:"( ) seen him before, I recognized him at once.", choices:["Having","Have","Had","Being"], a:"Having", j:"以前彼に会ったことがあったので、すぐに彼だと分かりました。"},
  {q:"You had better ( ) there alone.", choices:["not go","don't go","not to go","no go"], a:"not go", j:"そこへは一人で行かないほうがいい。"},
  {q:"I would rather ( ) at home.", choices:["stay","to stay","staying","stays"], a:"stay", j:"どちらかといえば家にいたいです。"},
  {q:"The news made her ( ).", choices:["happy","happily","to be happy","being happy"], a:"happy", j:"その知らせは彼女を幸せにしました。"},
  {q:"I saw a boy ( ) across the street.", choices:["running","run","to run","runs"], a:"running", j:"男の子が通りを走っているのを見ました。"},
  {q:"He is ( ) a teacher as a musician.", choices:["not so much","not only","as well","moreover"], a:"not so much", j:"彼は音楽家というよりはむしろ教師です。"},
  {q:"As ( ) as I know, he is honest.", choices:["far","long","much","soon"], a:"far", j:"私の知る限り、彼は正直です。"},
  {q:"( ) you hurry, you will miss the train.", choices:["Unless","If","When","As"], a:"Unless", j:"急がない限り、列車に乗り遅れますよ。"},
  {q:"He speaks as if he ( ) everything.", choices:["knew","knows","had known","know"], a:"knew", j:"彼はまるで何でも知っているかのように話します。"},
  {q:"It is time you ( ) to bed.", choices:["went","go","have gone","are going"], a:"went", j:"もう寝る時間ですよ。"},
  {q:"I wish I ( ) more money then.", choices:["had had","have","had","have had"], a:"had had", j:"あの時もっとお金があればよかったのに。"},
  {q:"But ( ) your help, I would have failed.", choices:["for","with","without","of"], a:"for", j:"あなたの助けがなかったら、私は失敗していただろう。"},
  {q:"She ( ) have lost her way.", choices:["must","can","should","may"], a:"must", j:"彼女は道に迷ったに違いありません。"},

  // --- 高度な語彙 (101-300) ---
  {q:"「abundant」の意味は？", choices:["豊富な","乏しい","貴重な","危険な"], a:"豊富な", j:"意味を選択してください"},
  {q:"「accurate」の意味は？", choices:["正確な","曖昧な","遅い","速い"], a:"正確な", j:"意味を選択してください"},
  {q:"「admire」の意味は？", choices:["称賛する","批判する","無視する","恐れる"], a:"称賛する", j:"意味を選択してください"},
  {q:"「alternative」の意味は？", choices:["代わりの","永遠の","古い","唯一の"], a:"代わりの", j:"意味を選択してください"},
  {q:"「ambition」の意味は？", choices:["大志/野心","絶望","怠慢","恐怖"], a:"大志/野心", j:"意味を選択してください"},
  {q:"「analyze」の意味は？", choices:["分析する","壊す","忘れる","歌う"], a:"分析する", j:"意味を選択してください"},
  {q:"「annual」の意味は？", choices:["年一回の","毎日の","毎月の","一過性の"], a:"年一回の", j:"意味を選択してください"},
  {q:"「anticipate」の意味は？", choices:["予期する","忘れる","後悔する","無視する"], a:"予期する", j:"意味を選択してください"},
  {q:"「apparent」の意味は？", choices:["明白な","隠れた","複雑な","曖昧な"], a:"明白な", j:"意味を選択してください"},
  {q:"「applicant」の意味は？", choices:["志願者","雇用主","教師","医者"], a:"志願者", j:"意味を選択してください"},
  {q:"「appreciate」の意味は？", choices:["正しく評価する/感謝する","無視する","壊す","疑う"], a:"正しく評価する/感謝する", j:"意味を選択してください"},
  {q:"「artificial」の意味は？", choices:["人工的な","自然な","古い","本物の"], a:"人工的な", j:"意味を選択してください"},
  {q:"「aspect」の意味は？", choices:["側面/外観","中心","裏側","理由"], a:"側面/外観", j:"意味を選択してください"},
  {q:"「association」の意味は？", choices:["協会/連想","個人","孤立","切断"], a:"協会/連想", j:"意味を選択してください"},
  {q:"「assumption」の意味は？", choices:["仮定","事実","証明","否定"], a:"仮定", j:"意味を選択してください"},
  {q:"「attitude」の意味は？", choices:["態度","高度","能力","知能"], a:"態度", j:"意味を選択してください"},
  {q:"「attribute」の意味は？", choices:["〜のせいにする/属性","防ぐ","助ける","壊す"], a:"〜のせいにする/属性", j:"意味を選択してください"},
  {q:"「audience」の意味は？", choices:["聴衆","話者","作者","読者"], a:"聴衆", j:"意味を選択してください"},
  {q:"「authority」の意味は？", choices:["権威/当局","服従","反抗","混乱"], a:"権威/当局", j:"意味を選択してください"},
  {q:"「available」の意味は？", choices:["利用可能な","高価な","空っぽの","壊れた"], a:"利用可能な", j:"意味を選択してください"},
  {q:"「aware」の意味は？", choices:["気づいて","忘れて","眠って","怒って"], a:"気づいて", j:"意味を選択してください"},
  {q:"「barrier」の意味は？", choices:["障壁","通路","窓","中心"], a:"障壁", j:"意味を選択してください"},
  {q:"「belief」の意味は？", choices:["信念","疑い","嘘","噂"], a:"信念", j:"意味を選択してください"},
  {q:"「capacity」の意味は？", choices:["収容能力/能力","欠乏","過去","理由"], a:"収容能力/能力", j:"意味を選択してください"},
  {q:"「circumstance」の意味は？", choices:["状況/環境","名前","場所","時間"], a:"状況/環境", j:"意味を選択してください"},
  {q:"「civilization」の意味は？", choices:["文明","自然","野蛮","過去"], a:"文明", j:"意味を選択してください"},
  {q:"「collapse」の意味は？", choices:["崩壊する","建設する","守る","変える"], a:"崩壊する", j:"意味を選択してください"},
  {q:"「combination」の意味は？", choices:["組み合わせ","分離","単独","孤立"], a:"組み合わせ", j:"意味を選択してください"},
  {q:"「commercial」の意味は？", choices:["商業的な","芸術的な","私的な","秘密の"], a:"商業的な", j:"意味を選択してください"},
  {q:"「commitment」の意味は？", choices:["献身/約束","裏切り","怠慢","拒絶"], a:"献身/約束", j:"意味を選択してください"},
  {q:"「compare」の意味は？", choices:["比較する","無視する","信じる","隠す"], a:"比較する", j:"意味を選択してください"},
  {q:"「competition」の意味は？", choices:["競争","協力","沈黙","平和"], a:"競争", j:"意味を選択してください"},
  {q:"「complex」の意味は？", choices:["複雑な","単純な","簡単な","新しい"], a:"複雑な", j:"意味を選択してください"},
  {q:"「comprehensive」の意味は？", choices:["包括的な","限定的な","単純な","静かな"], a:"包括的な", j:"意味を選択してください"},
  {q:"「conclusion」の意味は？", choices:["結論","序論","原因","過程"], a:"結論", j:"意味を選択してください"},
  {q:"「confidence」の意味は？", choices:["自信/信頼","不安","疑い","恐怖"], a:"自信/信頼", j:"意味を選択してください"},
  {q:"「consequence」の意味は？", choices:["結果","原因","理論","平穏"], a:"結果", j:"意味を選択してください"},
  {q:"「considerable」の意味は？", choices:["かなりの","わずかな","無視できる","抽象的な"], a:"かなりの", j:"意味を選択してください"},
  {q:"「constant」の意味は？", choices:["絶え間ない","一時的な","たまの","偶然の"], a:"絶え間ない", j:"意味を選択してください"},
  {q:"「construction」の意味は？", choices:["建設","破壊","自然","紛失"], a:"建設", j:"意味を選択してください"},
  {q:"「consumer」の意味は？", choices:["消費者","生産者","販売者","支配者"], a:"消費者", j:"意味を選択してください"},
  {q:"「contemporary」の意味は？", choices:["現代の","古代の","未来の","古い"], a:"現代の", j:"意味を選択してください"},
  {q:"「contribution」の意味は？", choices:["貢献","妨害","破壊","拒絶"], a:"貢献", j:"意味を選択してください"},
  {q:"「controversial」の意味は？", choices:["論争を呼ぶ","明白な","共通の","平和的な"], a:"論争を呼ぶ", j:"意味を選択してください"},
  {q:"「convenience」の意味は？", choices:["便利","不便","遠い","難しい"], a:"便利", j:"意味を選択してください"},
  {q:"「creative」の意味は？", choices:["創造的な","模倣の","古い","退屈な"], a:"創造的な", j:"意味を選択してください"},
  {q:"「critical」の意味は？", choices:["批判的な/重大な","褒める","些細な","安全な"], a:"批判的な/重大な", j:"意味を選択してください"},
  {q:"「curiosity」の意味は？", choices:["好奇心","無関心","恐怖","怒り"], a:"好奇心", j:"意味を選択してください"},
  {q:"「current」の意味は？", choices:["現在の/流れ","過去の","未来の","古い"], a:"現在の/流れ", j:"意味を選択してください"},
  {q:"「decade」の意味は？", choices:["10年間","1年間","1週間","100年間"], a:"10年間", j:"期間を選択してください"},
  {q:"「decline」の意味は？", choices:["衰退する/断る","増加する","受け入れる","始める"], a:"衰退する/断る", j:"意味を選択してください"},
  {q:"「definition」の意味は？", choices:["定義","推測","嘘","噂"], a:"定義", j:"意味を選択してください"},
  {q:"「deliberately」の意味は？", choices:["意図的に","偶然に","すぐに","決して"], a:"意図的に", j:"意味を選択してください"},
  {q:"「democracy」の意味は？", choices:["民主主義","独裁","混乱","軍事"], a:"民主主義", j:"意味を選択してください"},
  {q:"「demonstrate」の意味は？", choices:["証明する/実演する","隠す","壊す","忘れる"], a:"証明する/実演する", j:"意味を選択してください"},
  {q:"「departure」の意味は？", choices:["出発","到着","滞在","過去"], a:"出発", j:"意味を選択してください"},
  {q:"「description」の意味は？", choices:["描写","沈黙","破壊","忘却"], a:"描写", j:"意味を選択してください"},
  {q:"「desperate」の意味は？", choices:["自暴自棄の/必死の","幸せな","落ち着いた","怠慢な"], a:"自暴自棄の/必死の", j:"意味を選択してください"},
  {q:"「despite」の意味は？", choices:["〜にもかかわらず","〜のために","〜と一緒に","〜のせいで"], a:"〜にもかかわらず", j:"前置詞の意味を選択してください"},
  {q:"「destination」の意味は？", choices:["目的地","出発地","過去","現在"], a:"目的地", j:"意味を選択してください"},
  {q:"「determine」の意味は？", choices:["決定する","迷う","忘れる","不平を言う"], a:"決定する", j:"意味を選択してください"},
  {q:"「development」の意味は？", choices:["開発/発達","衰退","停止","破壊"], a:"開発/発達", j:"意味を選択してください"},
  {q:"「device」の意味は？", choices:["装置","原料","場所","理由"], a:"装置", j:"意味を選択してください"},
  {q:"「difference」の意味は？", choices:["違い","同じ","理由","結果"], a:"違い", j:"意味を選択してください"},
  {q:"「disadvantage」の意味は？", choices:["不利な点","利点","成功","勇気"], a:"不利な点", j:"意味を選択してください"},
  {q:"「disaster」の意味は？", choices:["災害","幸運","成功","平和"], a:"災害", j:"意味を選択してください"},
  {q:"「discipline」の意味は？", choices:["規律/訓練","混乱","遊び","怠慢"], a:"規律/訓練", j:"意味を選択してください"},
  {q:"「discovery」の意味は？", choices:["発見","紛失","破壊","伝統"], a:"発見", j:"意味を選択してください"},
  {q:"「discrimination」の意味は？", choices:["差別/識別","平等","協力","平和"], a:"差別/識別", j:"意味を選択してください"},
  {q:"「distinction」の意味は？", choices:["区別/卓越","混同","平凡","同一"], a:"区別/卓越", j:"意味を選択してください"},
  {q:"「distribute」の意味は？", choices:["分配する","集める","壊す","隠す"], a:"分配する", j:"意味を選択してください"},
  {q:"「diversity」の意味は？", choices:["多様性","単一性","同じ","終わり"], a:"多様性", j:"意味を選択してください"},
  {q:"「domestic」の意味は？", choices:["国内の/家庭の","外国の","遠い","新しい"], a:"国内の/家庭の", j:"意味を選択してください"},
  {q:"「dominate」の意味は？", choices:["支配する","従う","逃げる","助ける"], a:"支配する", j:"意味を選択してください"},
  {q:"「dramatic」の意味は？", choices:["劇的な","些細な","退屈な","古い"], a:"劇的な", j:"意味を選択してください"},
  {q:"「eager」の意味は？", choices:["熱望して","無関心な","嫌っている","眠い"], a:"熱望して", j:"意味を選択してください"},
  {q:"「economic」の意味は？", choices:["経済の","芸術の","科学の","宗教の"], a:"経済の", j:"意味を選択してください"},
  {q:"「efficient」の意味は？", choices:["効率的な","無駄な","遅い","古い"], a:"効率的な", j:"意味を選択してください"},
  {q:"「eliminate」の意味は？", choices:["取り除く","加える","守る","育てる"], a:"取り除く", j:"意味を選択してください"},
  {q:"「emphasize」の意味は？", choices:["強調する","無視する","忘れる","隠す"], a:"強調する", j:"意味を選択してください"},
  {q:"「employment」の意味は？", choices:["雇用","失業","遊び","休憩"], a:"雇用", j:"意味を選択してください"},
  {q:"「encounter」の意味は？", choices:["遭遇する","避ける","去る","隠す"], a:"遭遇する", j:"意味を選択してください"},
  {q:"「encourage」の意味は？", choices:["励ます","失望させる","止める","叱る"], a:"励ます", j:"意味を選択してください"},
  {q:"「enormous」の意味は？", choices:["巨大な","小さな","細い","短い"], a:"enormous", j:"意味を選択してください"},
  {q:"「environment」の意味は？", choices:["環境","経済","芸術","科学"], a:"環境", j:"意味を選択してください"},
  {q:"「equivalent」の意味は？", choices:["同等の","異なる","新しい","古い"], a:"同等の", j:"意味を選択してください"},
  {q:"「essential」の意味は？", choices:["不可欠な","不必要な","一時的な","伝統的な"], a:"essential", j:"意味を選択してください"},
  {q:"「establish」の意味は？", choices:["設立する","破壊する","去る","隠す"], a:"establish", j:"意味を選択してください"},
  {q:"「estimate」の意味は？", choices:["見積もる/推定する","決定する","忘れる","壊す"], a:"estimate", j:"意味を選択してください"},
  {q:"「evaluate」の意味は？", choices:["評価する","無視する","忘れる","隠す"], a:"evaluate", j:"意味を選択してください"},
  {q:"「evidence」の意味は？", choices:["証拠","推測","噂","嘘"], a:"evidence", j:"意味を選択してください"},
  {q:"「evolution」の意味は？", choices:["進化","退化","停止","破壊"], a:"evolution", j:"意味を選択してください"},
  {q:"「exaggerate」の意味は？", choices:["誇張する","過小評価する","隠す","述べる"], a:"exaggerate", j:"意味を選択してください"},
  {q:"「examine」の意味は？", choices:["調査する","無視する","壊す","忘れる"], a:"examine", j:"意味を選択してください"},
  {q:"「exception」の意味は？", choices:["例外","標準","規則","習慣"], a:"exception", j:"意味を選択してください"},
  {q:"「excessive」の意味は？", choices:["過度の","不足した","適度な","些細な"], a:"excessive", j:"意味を選択してください"},
  {q:"「executive」の意味は？", choices:["重役/執行権のある","平社員","生徒","患者"], a:"executive", j:"意味を選択してください"},
  {q:"「existence」の意味は？", choices:["存在","不在","虚無","過去"], a:"existence", j:"意味を選択してください"},
  {q:"「expansion」の意味は？", choices:["拡大","縮小","停止","維持"], a:"expansion", j:"意味を選択してください"},
  {q:"「expectation」の意味は？", choices:["期待","絶望","過去","現在"], a:"expectation", j:"意味を選択してください"},
  {q:"「expense」の意味は？", choices:["費用","利益","収入","貯金"], a:"expense", j:"意味を選択してください"},
  {q:"「experience」の意味は？", choices:["経験","実験","期待","表現"], a:"experience", j:"意味を選択してください"},
  {q:"「experiment」の意味は？", choices:["実験","経験","期待","表現"], a:"experiment", j:"意味を選択してください"},
  {q:"「expert」の意味は？", choices:["専門家","素人","初心者","子供"], a:"expert", j:"意味を選択してください"},
  {q:"「explanation」の意味は？", choices:["説明","質問","沈黙","命令"], a:"explanation", j:"意味を選択してください"},
  {q:"「exploration」の意味は？", choices:["探検/探究","保護","破壊","忘却"], a:"exploration", j:"意味を選択してください"},
  {q:"「export」の意味は？", choices:["輸出する","輸入する","作る","壊す"], a:"export", j:"意味を選択してください"},
  {q:"「expression」の意味は？", choices:["表現","抑制","隠蔽","沈黙"], a:"expression", j:"意味を選択してください"},
  {q:"「extend」の意味は？", choices:["延長する/広げる","短縮する","止める","壊す"], a:"extend", j:"意味を選択してください"},
  {q:"「extinguish」の意味は？", choices:["(火を)消す","つける","広げる","守る"], a:"extinguish", j:"意味を選択してください"},
  {q:"「extraordinary」の意味は？", choices:["並外れた","普通の","平凡な","些細な"], a:"extraordinary", j:"意味を選択してください"},
  {q:"「extreme」の意味は？", choices:["極端な","穏やかな","普通の","平均的な"], a:"extreme", j:"意味を選択してください"},
  {q:"「facility」の意味は？", choices:["施設/器用さ","困難","自然","過去"], a:"facility", j:"意味を選択してください"},
  {q:"「factor」の意味は？", choices:["要因","結果","偶然","無関係"], a:"factor", j:"意味を選択してください"},
  {q:"「failure」の意味は？", choices:["失敗","成功","努力","期待"], a:"failure", j:"意味を選択してください"},
  {q:"「faith」の意味は？", choices:["信仰/信頼","不信","疑い","嘘"], a:"faith", j:"意味を選択してください"},
  {q:"「familiar」の意味は？", choices:["よく知られた","未知の","怖い","新しい"], a:"familiar", j:"意味を選択してください"},
  {q:"「fascinating」の意味は？", choices:["魅惑的な","退屈な","不快な","怖い"], a:"fascinating", j:"意味を選択してください"},
  {q:"「feature」の意味は？", choices:["特徴","背景","理由","結果"], a:"feature", j:"意味を選択してください"},
  {q:"「federal」の意味は？", choices:["連邦の","州の","個人の","私的な"], a:"federal", j:"意味を選択してください"},
  {q:"「fee」の意味は？", choices:["料金","無料","寄付","利益"], a:"fee", j:"意味を選択してください"},
  {q:"「female」の意味は？", choices:["女性の","男性の","子供の","大人の"], a:"female", j:"意味を選択してください"},
  {q:"「fertile」の意味は？", choices:["肥沃な","不毛な","狭い","乾燥した"], a:"fertile", j:"意味を選択してください"},
  {q:"「fiction」の意味は？", choices:["小説/作り話","事実","歴史","科学"], a:"fiction", j:"意味を選択してください"},
  {q:"「figure」の意味は？", choices:["数字/姿/人物","沈黙","虚無","過去"], a:"figure", j:"意味を選択してください"},
  {q:"「financial」の意味は？", choices:["財政的な","芸術的な","科学的な","宗教的な"], a:"financial", j:"意味を選択してください"},
  {q:"「flexible」の意味は？", choices:["柔軟な","硬い","頑固な","古い"], a:"flexible", j:"意味を選択してください"},
  {q:"「flourish」の意味は？", choices:["繁栄する","衰退する","止まる","消える"], a:"flourish", j:"意味を選択してください"},
  {q:"「fluctuate」の意味は？", choices:["変動する","安定する","止まる","壊す"], a:"fluctuate", j:"意味を選択してください"},
  {q:"「focus」の意味は？", choices:["焦点/集中する","拡散する","無視する","忘れる"], a:"focus", j:"意味を選択してください"},
  {q:"「forbid」の意味は？", choices:["禁止する","許可する","助ける","勧める"], a:"forbid", j:"意味を選択してください"},
  {q:"「forecast」の意味は？", choices:["予測/予報","過去","結果","沈黙"], a:"forecast", j:"意味を選択してください"},
  {q:"「foreign」の意味は？", choices:["外国の","国内の","地元の","自分の"], a:"foreign", j:"意味を選択してください"},
  {q:"「formal」の意味は？", choices:["正式な/形式的な","非公式な","崩した","自由な"], a:"formal", j:"意味を選択してください"},
  {q:"「fortunate」の意味は？", choices:["幸運な","不運な","悲しい","怒った"], a:"fortunate", j:"意味を選択してください"},
  {q:"「foundation」の意味は？", choices:["基礎/財団","頂上","表面","偶然"], a:"foundation", j:"意味を選択してください"},
  {q:"「fragile」の意味は？", choices:["壊れやすい","丈夫な","新しい","高価な"], a:"fragile", j:"意味を選択してください"},
  {q:"「frequency」の意味は？", choices:["頻度/周波数","場所","理由","結果"], a:"frequency", j:"意味を選択してください"},
  {q:"「frequent」の意味は？", choices:["頻繁な","たまの","決してない","珍しい"], a:"frequent", j:"意味を選択してください"},
  {q:"「frustrated」の意味は？", choices:["欲求不満の","満足した","幸せな","眠い"], a:"frustrated", j:"意味を選択してください"},
  {q:"「fundamental」の意味は？", choices:["根本的な","些細な","一時的な","最新の"], a:"fundamental", j:"意味を選択してください"},
  {q:"「furniture」の意味は？", choices:["家具","衣服","道具","食器"], a:"furniture", j:"意味を選択してください"},
  {q:"「furthermore」の意味は？", choices:["さらに","しかし","代わりに","ついに"], a:"furthermore", j:"接続詞の意味を選択してください"},
  {q:"「future」の意味は？", choices:["未来","過去","現在","昨日"], a:"future", j:"意味を選択してください"},
  {q:"「gain」の意味は？", choices:["得る","失う","捨てる","壊す"], a:"gain", j:"意味を選択してください"},
  {q:"「gather」の意味は？", choices:["集める","散らす","去る","隠す"], a:"gather", j:"意味を選択してください"},
  {q:"「general」の意味は？", choices:["一般的な/大将","特別な","個別の","狭い"], a:"general", j:"意味を選択してください"},
  {q:"「generate」の意味は？", choices:["生み出す","破壊する","消費する","止める"], a:"generate", j:"意味を選択してください"},
  {q:"「generous」の意味は？", choices:["寛大な","けちな","厳しい","残酷な"], a:"generous", j:"意味を選択してください"},
  {q:"「genetic」の意味は？", choices:["遺伝の","環境の","教育の","習得した"], a:"genetic", j:"意味を選択してください"},
  {q:"「genius」の意味は？", choices:["天才","凡人","愚か者","子供"], a:"genius", j:"意味を選択してください"},
  {q:"「genuine」の意味は？", choices:["本物の","偽物の","安い","新しい"], a:"genuine", j:"意味を選択してください"},
  {q:"「gesture」の意味は？", choices:["身振り","言葉","沈黙","思考"], a:"gesture", j:"意味を選択してください"},
  {q:"「glance」の意味は？", choices:["ちらりと見る","凝視する","閉じる","歌う"], a:"glance", j:"意味を選択してください"},
  {q:"「global」の意味は？", choices:["地球規模の","地域の","個人の","狭い"], a:"global", j:"意味を選択してください"},
  {q:"「glory」の意味は？", choices:["栄光","恥","敗北","平凡"], a:"glory", j:"意味を選択してください"},
  {q:"「government」の意味は？", choices:["政府","企業","学校","市民"], a:"government", j:"意味を選択してください"},
  {q:"「gradual」の意味は？", choices:["徐々の","突然の","急激な","速い"], a:"gradual", j:"意味を選択してください"},
  {q:"「graduate」の意味は？", choices:["卒業する","入学する","休む","働く"], a:"graduate", j:"意味を選択してください"},
  {q:"「grateful」の意味は？", choices:["感謝している","怒っている","悲しい","恐れている"], a:"grateful", j:"意味を選択してください"},
  {q:"「gravity」の意味は？", choices:["重力/重大さ","浮力","軽薄","些細"], a:"gravity", j:"意味を選択してください"},
  {q:"「guarantee」の意味は？", choices:["保証する","疑う","壊す","忘れる"], a:"guarantee", j:"意味を選択してください"},
  {q:"「guidance」の意味は？", choices:["指導","放置","妨害","拒絶"], a:"guidance", j:"意味を選択してください"},
  {q:"「guilty」の意味は？", choices:["有罪の","無実の","正しい","賢い"], a:"guilty", j:"意味を選択してください"},
  {q:"「habit」の意味は？", choices:["習慣","性格","外見","知能"], a:"habit", j:"意味を選択してください"},
  {q:"「harvest」の意味は？", choices:["収穫","種まき","乾燥","洪水"], a:"harvest", j:"意味を選択してください"},
  {q:"「heritage」の意味は？", choices:["遺産","未来","破壊","忘却"], a:"heritage", j:"意味を選択してください"},
  {q:"「hesitate」の意味は？", choices:["ためらう","即決する","走る","叫ぶ"], a:"hesitate", j:"意味を選択してください"},
  {q:"「highlight」の意味は？", choices:["目立たせる/最良の部分","隠す","無視する","壊す"], a:"highlight", j:"意味を選択してください"},
  {q:"「history」の意味は？", choices:["歴史","未来","現在","数学"], a:"history", j:"意味を選択してください"},
  {q:"「honest」の意味は？", choices:["正直な","不正直な","悪い","賢い"], a:"honest", j:"意味を選択してください"},
  {q:"「honor」の意味は？", choices:["名誉","恥","嘘","罪"], a:"honor", j:"意味を選択してください"},
  {q:"「horizon」の意味は？", choices:["地平線","頂上","中心","底"], a:"horizon", j:"意味を選択してください"},
  {q:"「hospitality」の意味は？", choices:["もてなし","冷淡","拒絶","敵意"], a:"hospitality", j:"意味を選択してください"},
  {q:"「hostile」の意味は？", choices:["敵意のある","友好的な","親切な","静かな"], a:"hostile", j:"意味を選択してください"},
  {q:"「household」の意味は？", choices:["世帯/家庭","個人","会社","政府"], a:"household", j:"意味を選択してください"},
  {q:"「huge」の意味は？", choices:["巨大な","小さな","細い","短い"], a:"huge", j:"意味を選択してください"},
  {q:"「humanity」の意味は？", choices:["人類/人間性","動物","機械","自然"], a:"humanity", j:"意味を選択してください"},
  {q:"「humble」の意味は？", choices:["謙虚な/卑しい","傲慢な","有名な","高価な"], a:"humble", j:"意味を選択してください"},
  {q:"「hypothesis」の意味は？", choices:["仮説","事実","法律","文化"], a:"hypothesis", j:"意味を選択してください"},
  {q:"「identify」の意味は？", choices:["特定する/同一視する","隠す","壊す","忘れる"], a:"identify", j:"意味を選択してください"},
  {q:"「ignore」の意味は？", choices:["無視する","注目する","信じる","助ける"], a:"ignore", j:"意味を選択してください"},
  {q:"「illegal」の意味は？", choices:["違法の","合法の","正しい","公式の"], a:"illegal", j:"意味を選択してください"},
  {q:"「illusion」の意味は？", choices:["幻想/錯覚","現実","真実","証明"], a:"illusion", j:"意味を選択してください"},
  {q:"「illustrate」の意味は？", choices:["説明する/例示する","隠す","壊す","忘れる"], a:"illustrate", j:"意味を選択してください"},
  {q:"「imagination」の意味は？", choices:["想像力","現実","事実","知識"], a:"imagination", j:"意味を選択してください"},
  {q:"「immediate」の意味は？", choices:["即座の","遅い","遠い","過去の"], a:"immediate", j:"意味を選択してください"},
  {q:"「immigrant」の意味は？", choices:["(入国)移民","出国者","観光客","住民"], a:"immigrant", j:"意味を選択してください"},
  {q:"「impact」の意味は？", choices:["影響/衝撃","無視","安らぎ","沈黙"], a:"impact", j:"意味を選択してください"},
  {q:"「implement」の意味は？", choices:["実行する/道具","中止する","壊す","忘れる"], a:"implement", j:"意味を選択してください"},
  {q:"「imply」の意味は？", choices:["暗示する","明示する","否定する","忘れる"], a:"imply", j:"意味を選択してください"},
  {q:"「important」の意味は？", choices:["重要な","些細な","面白い","古い"], a:"important", j:"意味を選択してください"},
  {q:"「impose」の意味は？", choices:["課す/押しつける","取り除く","助ける","許す"], a:"impose", j:"意味を選択してください"},
  {q:"「impressive」の意味は？", choices:["印象的な","退屈な","普通の","悪い"], a:"impressive", j:"意味を選択してください"},
  {q:"「improve」の意味は？", choices:["改善する","悪化させる","維持する","変える"], a:"improve", j:"意味を選択してください"},
  {q:"「incentive」の意味は？", choices:["動機/刺激","妨害","退屈","停止"], a:"incentive", j:"意味を選択してください"},
  {q:"「incident」の意味は？", choices:["出来事/事件","平和","日常","沈黙"], a:"incident", j:"意味を選択してください"},
  {q:"「include」の意味は？", choices:["含む","除く","壊す","捨てる"], a:"include", j:"意味を選択してください"},
  {q:"「income」の意味は？", choices:["収入","支出","借金","費用"], a:"income", j:"意味を選択してください"},
  {q:"「increase」の意味は？", choices:["増加する","減少する","止まる","消える"], a:"increase", j:"意味を選択してください"},
  {q:"「incredible」の意味は？", choices:["信じられない","ありふれた","本当の","退屈な"], a:"incredible", j:"意味を選択してください"},
  {q:"「independent」の意味は？", choices:["独立した","依存した","共通の","弱い"], a:"independent", j:"意味を選択してください"},
  {q:"「indicate」の意味は？", choices:["指し示す","隠す","壊す","忘れる"], a:"indicate", j:"意味を選択してください"},
  {q:"「individual」の意味は？", choices:["個人の/個体","集団の","共通の","公式の"], a:"individual", j:"意味を選択してください"},
  {q:"「inevitable」の意味は？", choices:["避けられない","回避可能な","偶然の","珍しい"], a:"inevitable", j:"意味を選択してください"},
  {q:"「influence」の意味は？", choices:["影響","結果","原因","理論"], a:"influence", j:"意味を選択してください"},
  {q:"「inform」の意味は？", choices:["知らせる","隠す","黙る","忘れる"], a:"inform", j:"意味を選択してください"},
  {q:"「ingredient」の意味は？", choices:["材料/成分","道具","場所","時間"], a:"ingredient", j:"意味を選択してください"},
  {q:"「initial」の意味は？", choices:["最初の","最後の","中間の","現在の"], a:"initial", j:"意味を選択してください"},
  {q:"「initiative」の意味は？", choices:["主導権/自発性","服従","怠慢","停止"], a:"initiative", j:"意味を選択してください"},
  {q:"「injury」の意味は？", choices:["負傷","健康","回復","運動"], a:"injury", j:"意味を選択してください"},
  {q:"「innocent」の意味は？", choices:["無実の/無邪気な","有罪の","悪い","賢い"], a:"innocent", j:"意味を選択してください"},
  {q:"「innovation」の意味は？", choices:["革新","伝統","保守","破壊"], a:"innovation", j:"意味を選択してください"},
  {q:"「input」の意味は？", choices:["入力/投入","出力","消失","停止"], a:"input", j:"意味を選択してください"},
  {q:"「inquiry」の意味は？", choices:["調査/質問","回答","沈黙","無視"], a:"inquiry", j:"意味を選択してください"},
  {q:"「insight」の意味は？", choices:["洞察力","無知","混乱","外見"], a:"insight", j:"意味を選択してください"},
  {q:"「insist」の意味は？", choices:["主張する","譲歩する","黙る","忘れる"], a:"insist", j:"意味を選択してください"},
  {q:"「inspire」の意味は？", choices:["奮起させる/着想を与える","失望させる","眠らせる","止める"], a:"inspire", j:"意味を選択してください"},
  {q:"「instance」の意味は？", choices:["例/場合","全体","過去","理由"], a:"instance", j:"意味を選択してください"},
  {q:"「instead」の意味は？", choices:["代わりに","一緒に","決して","すぐに"], a:"instead", j:"意味を選択してください"},
  {q:"「instinct」の意味は？", choices:["本能","学習","理性","知識"], a:"instinct", j:"意味を選択してください"},
  {q:"「instruction」の意味は？", choices:["指示/教育","混乱","放置","遊び"], a:"instruction", j:"意味を選択してください"},
  {q:"「instrument」の意味は？", choices:["器具/楽器","建物","食べ物","人間"], a:"instrument", j:"意味を選択してください"},
  {q:"「insult」の意味は？", choices:["侮辱する","褒める","助ける","祝う"], a:"insult", j:"意味を選択してください"},
  {q:"「insurance」の意味は？", choices:["保険","危険","損失","浪費"], a:"insurance", j:"意味を選択してください"},
  {q:"「intellectual」の意味は？", choices:["知的な","感情的な","身体的な","野蛮な"], a:"intellectual", j:"意味を選択してください"},
  {q:"「intelligence」の意味は？", choices:["知能/情報","愚かさ","沈黙","運動"], a:"intelligence", j:"意味を選択してください"},
  {q:"「intend」の意味は？", choices:["意図する","忘れる","避ける","止める"], a:"intend", j:"意味を選択してください"},
  {q:"「intense」の意味は？", choices:["激しい/強烈な","穏やかな","弱い","些細な"], a:"intense", j:"意味を選択してください"},
  {q:"「interaction」の意味は？", choices:["交流/相互作用","孤立","切断","静止"], a:"interaction", j:"意味を選択してください"},
  {q:"「interest」の意味は？", choices:["興味/利子","退屈","苦痛","怒り"], a:"interest", j:"意味を選択してください"},
  {q:"「interfere」の意味は？", choices:["干渉する/邪魔する","助ける","離れる","許す"], a:"interfere", j:"意味を選択してください"},
  {q:"「internal」の意味は？", choices:["内部の","外部の","表面の","遠い"], a:"internal", j:"意味を選択してください"},
  {q:"「international」の意味は？", choices:["国際的な","国内の","地元の","狭い"], a:"international", j:"意味を選択してください"},
  {q:"「interpret」の意味は？", choices:["解釈する/通訳する","無視する","忘れる","隠す"], a:"interpret", j:"意味を選択してください"},
  {q:"「interrupt」の意味は？", choices:["中断させる","続ける","助ける","始める"], a:"interrupt", j:"意味を選択してください"},
  {q:"「interval」の意味は？", choices:["間隔","連続","中心","終わり"], a:"interval", j:"意味を選択してください"},
  {q:"「interview」の意味は？", choices:["面接","睡眠","遊び","休憩"], a:"interview", j:"意味を選択してください"},
  {q:"「intimate」の意味は？", choices:["親密な","疎遠な","怖い","新しい"], a:"intimate", j:"意味を選択してください"},
  {q:"「introduce」の意味は？", choices:["紹介する/導入する","隠す","去る","終わる"], a:"introduce", j:"意味を選択してください"},
  {q:"「invade」の意味は？", choices:["侵略する","守る","去る","助ける"], a:"invade", j:"意味を選択してください"},
  {q:"「invention」の意味は？", choices:["発明","伝統","破壊","紛失"], a:"invention", j:"意味を選択してください"},
  {q:"「invest」の意味は？", choices:["投資する","消費する","捨てる","盗む"], a:"invest", j:"意味を選択してください"},
  {q:"「investigate」の意味は？", choices:["調査する","無視する","忘れる","壊す"], a:"investigate", j:"意味を選択してください"},
  {q:"「invisible」の意味は？", choices:["目に見えない","明白な","明るい","派手な"], a:"invisible", j:"意味を選択してください"},
  {q:"「invite」の意味は？", choices:["招待する","拒絶する","去る","叱る"], a:"invite", j:"意味を選択してください"},
  {q:"「involve」の意味は？", choices:["巻き込む/含む","除外する","離す","壊す"], a:"involve", j:"意味を選択してください"},
  {q:"「irony」の意味は？", choices:["皮肉","賞賛","事実","真実"], a:"irony", j:"意味を選択してください"},
  {q:"「isolate」の意味は？", choices:["孤立させる","繋ぐ","混ぜる","助ける"], a:"isolate", j:"意味を選択してください"},
  {q:"「issue」の意味は？", choices:["問題/発行","解決","沈黙","過去"], a:"issue", j:"意味を選択してください"},
  {q:"「item」の意味は？", choices:["項目/品物","全体","理由","時間"], a:"item", j:"意味を選択してください"},
  {q:"「jail」の意味は？", choices:["監獄","学校","病院","公園"], a:"jail", j:"意味を選択してください"},
  {q:"「jealous」の意味は？", choices:["嫉妬深い","寛大な","幸せな","眠い"], a:"jealous", j:"意味を選択してください"},
  {q:"「joint」の意味は？", choices:["共同の/関節","単独の","個人の","秘密の"], a:"joint", j:"意味を選択してください"},
  {q:"「journal」の意味は？", choices:["日誌/雑誌","小説","沈黙","過去"], a:"journal", j:"意味を選択してください"},
  {q:"「journey」の意味は？", choices:["旅","仕事","休憩","睡眠"], a:"journey", j:"意味を選択してください"},
  {q:"「joy」の意味は？", choices:["喜び","悲しみ","怒り","恐怖"], a:"joy", j:"意味を選択してください"},
  {q:"「judge」の意味は？", choices:["判断する/裁判官","従う","遊ぶ","眠る"], a:"judge", j:"意味を選択してください"},
  {q:"「judicial」の意味は？", choices:["司法の","経済の","芸術の","個人的な"], a:"judicial", j:"意味を選択してください"},
  {q:"「junction」の意味は？", choices:["合流点","終点","中心","直線"], a:"junction", j:"意味を選択してください"},
  {q:"「junior」の意味は？", choices:["年下の/下位の","年上の","同じの","古い"], a:"junior", j:"意味を選択してください"},
  {q:"「jury」の意味は？", choices:["陪審員","被告","弁護士","警察"], a:"jury", j:"意味を選択してください"},
  {q:"「just」の意味は？", choices:["公正な/ただの","不当な","悪い","古い"], a:"just", j:"意味を選択してください"},
  {q:"「justice」の意味は？", choices:["正義","悪","嘘","犯罪"], a:"justice", j:"意味を選択してください"},
  {q:"「justify」の意味は？", choices:["正当化する","批判する","壊す","隠す"], a:"justify", j:"意味を選択してください"},
  {q:"「keen」の意味は？", choices:["鋭い/熱心な","鈍い","退屈な","古い"], a:"keen", j:"意味を選択してください"},
  {q:"「keep」の意味は？", choices:["保つ/飼う","捨てる","壊す","去る"], a:"keep", j:"意味を選択してください"},
  {q:"「kidnap」の意味は？", choices:["誘拐する","助ける","守る","呼ぶ"], a:"kidnap", j:"意味を選択してください"},
  {q:"「kindness」の意味は？", choices:["親切","残酷","怒り","恐怖"], a:"kindness", j:"意味を選択してください"},
  {q:"「kingdom」の意味は？", choices:["王国","共和国","都市","村"], a:"kingdom", j:"意味を選択してください"},
  {q:"「kneel」の意味は？", choices:["ひざまずく","立つ","走る","跳ぶ"], a:"kneel", j:"意味を選択してください"},
  {q:"「knowledge」の意味は？", choices:["知識","無知","夢","嘘"], a:"knowledge", j:"意味を選択してください"}
];
