// questions.js - ENGLISH QUEST 300 QUESTIONS FULL DATA
const masterQuestions = [
  // --- 文法セクション (1-100) ---
  {q:"I (  ) my homework yet.", choices:["haven't finished","didn't finish","don't finish","finished"], a:"haven't finished"},
  {q:"Tokyo is the city (  ) I was born.", choices:["where","which","that","there"], a:"where"},
  {q:"If I (  ) a bird, I would fly.", choices:["were","am","was","be"], a:"were"},
  {q:"The letter (  ) by Mary yesterday.", choices:["was written","wrote","is written","writes"], a:"was written"},
  {q:"I'm looking forward to (  ) you.", choices:["seeing","see","seen","saw"], a:"seeing"},
  {q:"He is (  ) than me.", choices:["taller","tallest","more tall","tall"], a:"taller"},
  {q:"You (  ) go there alone. It's dangerous.", choices:["mustn't","don't have to","needn't","doesn't"], a:"mustn't"},
  {q:"She (  ) lunch when I called her.", choices:["was eating","eats","ate","has eaten"], a:"was eating"},
  {q:"I have (  ) been to Hokkaido.", choices:["never","ever","yet","already"], a:"never"},
  {q:"This is the book (  ) I bought yesterday.", choices:["which","who","where","when"], a:"which"},
  {q:"My brother (  ) English for three years.", choices:["has studied","studies","studied","is studying"], a:"has studied"},
  {q:"I want (  ) something cold to drink.", choices:["to have","having","had","have"], a:"to have"},
  {q:"It is difficult (  ) me to read this.", choices:["for","of","to","with"], a:"for"},
  {q:"They (  ) each other since they were kids.", choices:["have known","know","knew","knowing"], a:"have known"},
  {q:"You don't (  ) to hurry.", choices:["have","must","need","should"], a:"have"},
  {q:"I'm too tired (  ) walk.", choices:["to","for","that","and"], a:"to"},
  {q:"He told me (  ) be late.", choices:["not to","to not","don't","no"], a:"not to"},
  {q:"I remember (  ) him before.", choices:["meeting","to meet","met","meet"], a:"meeting"},
  {q:"The news made us (  ).", choices:["happy","happily","to be happy","happiness"], a:"happy"},
  {q:"How (  ) have you been here?", choices:["long","often","many","much"], a:"long"},
  {q:"I (  ) to the station when it started to rain.", choices:["was walking","walked","walk","have walked"], a:"was walking"},
  {q:"This watch (  ) in Switzerland.", choices:["was made","made","is making","makes"], a:"was made"},
  {q:"He (  ) to be a doctor when he grows up.", choices:["wants","want","is wanting","wanted"], a:"wants"},
  {q:"(  ) you ever seen a koala?", choices:["Have","Did","Do","Are"], a:"Have"},
  {q:"She (  ) speak English very well.", choices:["can","is","does","has"], a:"can"},
  {q:"I (  ) seen that movie twice.", choices:["have","am","did","was"], a:"have"},
  {q:"The cake (  ) by my sister.", choices:["was made","made","makes","is making"], a:"was made"},
  {q:"(  ) you like to join us?", choices:["Would","Do","Will","Can"], a:"Would"},
  {q:"I (  ) finished my work.", choices:["have already","already have","am already","did already"], a:"have already"},
  {q:"He (  ) to school by bus.", choices:["goes","go","going","is go"], a:"goes"},
  {q:"We (  ) playing tennis then.", choices:["were","are","was","did"], a:"were"},
  {q:"This is the (  ) interesting book I've ever read.", choices:["most","more","much","very"], a:"most"},
  {q:"You (  ) clean your room.", choices:["should","are","do","have"], a:"should"},
  {q:"I (  ) lunch now.", choices:["am having","have","had","am have"], a:"am having"},
  {q:"She (  ) to Kyoto yesterday.", choices:["went","goes","gone","has gone"], a:"went"},
  {q:"He (  ) English since 2010.", choices:["has studied","studies","studied","is studying"], a:"has studied"},
  {q:"It (  ) raining for two hours.", choices:["has been","is","was","be"], a:"has been"},
  {q:"I (  ) a letter when he came.", choices:["was writing","write","wrote","have written"], a:"was writing"},
  {q:"This (  ) be true.", choices:["cannot","not","isn't","doesn't"], a:"cannot"},
  {q:"May I (  ) your name?", choices:["have","ask","know","all of these"], a:"all of these"},
  {q:"I (  ) go there if I were you.", choices:["would","will","shall","can"], a:"would"},
  {q:"He (  ) me that he was tired.", choices:["told","said","spoke","talked"], a:"told"},
  {q:"(  ) you busy now?", choices:["Are","Do","Is","Have"], a:"Are"},
  {q:"I (  ) her tomorrow.", choices:["will see","saw","see","have seen"], a:"will see"},
  {q:"She (  ) her key.", choices:["has lost","is lost","lost","loses"], a:"has lost"},
  {q:"It (  ) getting dark.", choices:["is","does","has","was"], a:"is"},
  {q:"I (  ) to go home.", choices:["want","am wanting","wants","wanted"], a:"want"},
  {q:"He (  ) tennis every Sunday.", choices:["plays","play","playing","played"], a:"plays"},
  {q:"We (  ) known him for a long time.", choices:["have","are","do","did"], a:"have"},
  {q:"She (  ) to me.", choices:["is talking","talks","talked","all of these"], a:"all of these"},
  {q:"(  ) you ever been to London?", choices:["Have","Did","Do","Were"], a:"Have"},
  {q:"I (  ) my homework tomorrow.", choices:["will do","do","did","have done"], a:"will do"},
  {q:"He (  ) very busy yesterday.", choices:["was","is","were","did"], a:"was"},
  {q:"(  ) you speak Japanese?", choices:["Can","Are","Do","Is"], a:"Can"},
  {q:"I (  ) like sushi.", choices:["don't","am not","not","doesn't"], a:"don't"},
  {q:"She (  ) a teacher.", choices:["is","am","are","be"], a:"is"},
  {q:"We (  ) happy.", choices:["are","is","am","be"], a:"are"},
  {q:"They (  ) in the park.", choices:["are","is","am","be"], a:"are"},
  {q:"I (  ) a student.", choices:["am","is","are","be"], a:"am"},
  {q:"He (  ) a car.", choices:["has","have","is","does"], a:"has"},
  {q:"She (  ) a dog.", choices:["has","have","is","does"], a:"has"},
  {q:"I (  ) two sisters.", choices:["have","has","am","do"], a:"have"},
  {q:"(  ) he like apples?", choices:["Does","Do","Is","Has"], a:"Does"},
  {q:"(  ) they go to school?", choices:["Do","Does","Are","Have"], a:"Do"},
  {q:"I (  ) not know.", choices:["do","am","is","have"], a:"do"},
  {q:"She (  ) not like milk.", choices:["does","do","is","has"], a:"does"},
  {q:"It (  ) a pen.", choices:["is","am","are","be"], a:"is"},
  {q:"That (  ) my house.", choices:["is","am","are","be"], a:"is"},
  {q:"These (  ) my books.", choices:["are","is","am","be"], a:"are"},
  {q:"Those (  ) birds.", choices:["are","is","am","be"], a:"are"},
  {q:"(  ) this your pen?", choices:["Is","Am","Are","Do"], a:"Is"},
  {q:"(  ) these your keys?", choices:["Are","Is","Am","Do"], a:"Are"},
  {q:"Who (  ) he?", choices:["is","am","are","be"], a:"is"},
  {q:"Where (  ) you from?", choices:["are","is","am","be"], a:"are"},
  {q:"What (  ) this?", choices:["is","am","are","be"], a:"is"},
  {q:"When (  ) your birthday?", choices:["is","am","are","be"], a:"is"},
  {q:"How (  ) you?", choices:["are","is","am","be"], a:"are"},
  {q:"Why (  ) you late?", choices:["are","is","am","be"], a:"are"},
  {q:"(  ) is that man?", choices:["Who","What","Where","When"], a:"Who"},
  {q:"(  ) color is it?", choices:["What","Who","Where","When"], a:"What"},
  {q:"(  ) is my bag?", choices:["Where","What","Who","When"], a:"Where"},
  {q:"(  ) do you get up?", choices:["When","What","Who","Where"], a:"When"},
  {q:"(  ) do you like it?", choices:["Why","What","Who","Where"], a:"Why"},
  {q:"(  ) much is it?", choices:["How","What","Who","Where"], a:"How"},
  {q:"(  ) many apples do you have?", choices:["How","What","Who","Where"], a:"How"},
  {q:"I (  ) go now.", choices:["must","am","do","have"], a:"must"},
  {q:"You (  ) not smoke here.", choices:["must","are","do","have"], a:"must"},
  {q:"Can I (  ) you?", choices:["help","helping","helped","helps"], a:"help"},
  {q:"He (  ) play the guitar.", choices:["can","is","does","has"], a:"can"},
  {q:"May I (  ) in?", choices:["come","coming","came","comes"], a:"come"},
  {q:"You (  ) go home.", choices:["may","are","do","have"], a:"may"},
  {q:"Shall we (  ) tennis?", choices:["play","playing","played","plays"], a:"play"},
  {q:"Will you (  ) me?", choices:["help","helping","helped","helps"], a:"help"},
  {q:"I (  ) like some water.", choices:["would","will","shall","can"], a:"would"},
  {q:"He (  ) to be a doctor.", choices:["wants","want","is wanting","wanted"], a:"wants"},
  {q:"She (  ) like to dance.", choices:["likes","like","is liking","liked"], a:"likes"},
  {q:"They (  ) playing soccer.", choices:["like","likes","is liking","liked"], a:"like"},
  {q:"I (  ) playing the piano.", choices:["enjoy","enjoys","enjoying","enjoyed"], a:"enjoy"},
  {q:"He (  ) to study English.", choices:["needs","need","needing","needed"], a:"needs"},
  {q:"She (  ) to buy a new car.", choices:["hopes","hope","hoping","hoped"], a:"hopes"},

  // --- 単語セクション (101-300) ---
  // A-Z順などの重要単語200問
  {q:"「environment」の意味は？", choices:["環境","政府","期待","改善"], a:"環境"},
  {q:"「opportunity」の意味は？", choices:["機会","危機","安定","終わり"], a:"機会"},
  {q:"「accept」の意味は？", choices:["受け入れる","拒絶する","期待する","準備する"], a:"受け入れる"},
  {q:"「achievement」の意味は？", choices:["達成","失敗","娯楽","状況"], a:"達成"},
  {q:"「admire」の意味は？", choices:["賞賛する","非難する","無視する","改善する"], a:"賞賛する"},
  {q:"「affect」の意味は？", choices:["影響を与える","解決する","提供する","妨害する"], a:"影響を与える"},
  {q:"「amount」の意味は？", choices:["量","質","形","色"], a:"量"},
  {q:"「analysis」の意味は？", choices:["分析","建設","破壊","感覚"], a:"分析"},
  {q:"「appearance」の意味は？", choices:["外見","性格","記憶","能力"], a:"外見"},
  {q:"「appointment」の意味は？", choices:["予約/約束","偶然","失望","成功"], a:"予約/約束"},
  {q:"「appropriate」の意味は？", choices:["適切な","不快な","複雑な","巨大な"], a:"適切な"},
  {q:"「artificial」の意味は？", choices:["人工の","自然の","伝統的な","最近の"], a:"人工の"},
  {q:"「avoid」の意味は？", choices:["避ける","直面する","招待する","繰り返す"], a:"避ける"},
  {q:"「behavior」の意味は？", choices:["振る舞い","感情","知能","外見"], a:"振る舞い"},
  {q:"「belief」の意味は？", choices:["信念","疑い","恐怖","嘘"], a:"信念"},
  {q:"「capacity」の意味は？", choices:["収容能力","速度","距離","重さ"], a:"収容能力"},
  {q:"「climate」の意味は？", choices:["気候","天気","景色","地質"], a:"気候"},
  {q:"「comfortable」の意味は？", choices:["快適な","退屈な","苦しい","高価な"], a:"快適な"},
  {q:"「compare」の意味は？", choices:["比較する","同一視する","無視する","愛する"], a:"比較する"},
  {q:"「competition」の意味は？", choices:["競争","協力","平和","友情"], a:"競争"},
  {q:"「confidence」の意味は？", choices:["自信","不安","怒り","驚き"], a:"自信"},
  {q:"「consider」の意味は？", choices:["よく考える","無視する","決める","忘れる"], a:"よく考える"},
  {q:"「consumer」の意味は？", choices:["消費者","生産者","販売者","管理者"], a:"消費者"},
  {q:"「contain」の意味は？", choices:["含む","漏らす","除く","嫌う"], a:"含む"},
  {q:"「convenient」の意味は？", choices:["便利な","不便な","遠い","遅い"], a:"便利な"},
  {q:"「create」の意味は？", choices:["創造する","破壊する","消費する","隠す"], a:"創造する"},
  {q:"「critical」の意味は？", choices:["批判的な/重大な","安全な","些細な","陽気な"], a:"批判的な/重大な"},
  {q:"「damage」の意味は？", choices:["損害","利益","回復","建設"], a:"損害"},
  {q:"「decision」の意味は？", choices:["決定","迷い","提案","質問"], a:"決定"},
  {q:"「describe」の意味は？", choices:["描写する","沈黙する","行動する","忘れる"], a:"描写する"},
  {q:"「destroy」の意味は？", choices:["破壊する","作る","育てる","選ぶ"], a:"破壊する"},
  {q:"「detail」の意味は？", choices:["詳細","大枠","過去","未来"], a:"詳細"},
  {q:"「develop」の意味は？", choices:["発達させる","停止する","戻る","捨てる"], a:"発達させる"},
  {q:"「difference」の意味は？", choices:["違い","同じ","合計","理由"], a:"違い"},
  {q:"「disappear」の意味は？", choices:["消える","現れる","増える","留まる"], a:"消える"},
  {q:"「discovery」の意味は？", choices:["発見","発明","隠蔽","喪失"], a:"発見"},
  {q:"「discuss」の意味は？", choices:["議論する","同意する","拒否する","歌う"], a:"議論する"},
  {q:"「distance」の意味は？", choices:["距離","時間","速度","重さ"], a:"距離"},
  {q:"「domestic」の意味は？", choices:["国内の/家庭の","外国の","野生の","都会の"], a:"国内の/家庭の"},
  {q:"「economy」の意味は？", choices:["経済","政治","宗教","芸術"], a:"経済"},
  {q:"「effort」の意味は？", choices:["努力","才能","運","結果"], a:"努力"},
  {q:"「emergency」の意味は？", choices:["緊急事態","平和","日常","訓練"], a:"緊急事態"},
  {q:"「encourage」の意味は？", choices:["勇気づける","妨げる","叱る","忘れる"], a:"勇気づける"},
  {q:"「entire」の意味は？", choices:["全体の","一部の","空の","重い"], a:"全体の"},
  {q:"「essential」の意味は？", choices:["不可欠な","不要な","新しい","古い"], a:"不可欠な"},
  {q:"「evidence」の意味は？", choices:["証拠","推測","嘘","物語"], a:"証拠"},
  {q:"「experience」の意味は？", choices:["経験","空想","睡眠","食事"], a:"経験"},
  {q:"「explain」の意味は？", choices:["説明する","聞く","黙る","隠す"], a:"説明する"},
  {q:"「express」の意味は？", choices:["表現する","抑える","包む","送る"], a:"表現する"},
  {q:"「facility」の意味は？", choices:["施設","能力","困難","偶然"], a:"施設"},
  {q:"「factor」の意味は？", choices:["要因","結果","合計","答え"], a:"要因"},
  {q:"「favorite」の意味は？", choices:["お気に入りの","嫌いな","普通の","有名な"], a:"お気に入りの"},
  {q:"「flexible」の意味は？", choices:["柔軟な","硬い","壊れた","高価な"], a:"柔軟な"},
  {q:"「focus」の意味は？", choices:["集中する","分散する","無視する","眠る"], a:"集中する"},
  {q:"「foreign」の意味は？", choices:["外国の","国内の","地元の","古い"], a:"外国の"},
  {q:"「frequent」の意味は？", choices:["頻繁な","稀な","遅い","速い"], a:"頻繁な"},
  {q:"「generation」の意味は？", choices:["世代","個人","国家","世界"], a:"世代"},
  {q:"「global」の意味は？", choices:["世界的な","地域の","狭い","個人的な"], a:"世界的な"},
  {q:"「government」の意味は？", choices:["政府","市場","学校","家族"], a:"政府"},
  {q:"「gradually」の意味は？", choices:["徐々に","突然","永遠に","決して"], a:"徐々に"},
  {q:"「habit」の意味は？", choices:["習慣","趣味","仕事","夢"], a:"習慣"},
  {q:"「heritage」の意味は？", choices:["遺産","未来","発明","贈り物"], a:"遺産"},
  {q:"「hesitate」の意味は？", choices:["ためらう","決断する","走る","叫ぶ"], a:"ためらう"},
  {q:"「identify」の意味は？", choices:["特定する","隠す","忘れる","失う"], a:"特定する"},
  {q:"「ignore」の意味は？", choices:["無視する","注目する","助ける","叱る"], a:"無視する"},
  {q:"「imagine」の意味は？", choices:["想像する","見る","触る","聞く"], a:"想像する"},
  {q:"「immediate」の意味は？", choices:["即座の","遅い","遠い","過去の"], a:"即座の"},
  {q:"「impact」の意味は？", choices:["影響/衝撃","無視","安定","維持"], a:"影響/衝撃"},
  {q:"「improve」の意味は？", choices:["改善する","悪化させる","維持する","止める"], a:"改善する"},
  {q:"「independent」の意味は？", choices:["独立した","依存した","弱い","共通の"], a:"独立した"},
  {q:"「influence」の意味は？", choices:["影響","結果","原因","終わり"], a:"影響"},
  {q:"「information」の意味は？", choices:["情報","噂","秘密","沈黙"], a:"情報"},
  {q:"「injury」の意味は？", choices:["怪我","健康","運動","回復"], a:"怪我"},
  {q:"「innocent」の意味は？", choices:["無実の/純真な","有罪の","悪い","賢い"], a:"無実の/純真な"},
  {q:"「intelligence」の意味は？", choices:["知能","体力","外見","年齢"], a:"知能"},
  {q:"「intention」の意味は？", choices:["意図","偶然","結果","過去"], a:"意図"},
  {q:"「interrupt」の意味は？", choices:["中断させる","続ける","助ける","始める"], a:"中断させる"},
  {q:"「introduce」の意味は？", choices:["紹介する","去る","隠す","壊す"], a:"紹介する"},
  {q:"「invention」の意味は？", choices:["発明","発見","盗難","伝統"], a:"発明"},
  {q:"「investigate」の意味は？", choices:["調査する","無視する","報告する","遊ぶ"], a:"調査する"},
  {q:"「judge」の意味は？", choices:["判断する","迷う","尋ねる","信じる"], a:"判断する"},
  {q:"「knowledge」の意味は？", choices:["知識","無知","経験","才能"], a:"知識"},
  {q:"「landscape」の意味は？", choices:["風景","都会","建物","地図"], a:"風景"},
  {q:"「lecture」の意味は？", choices:["講義","雑談","歌","遊び"], a:"講義"},
  {q:"「limit」の意味は？", choices:["制限","自由","拡大","無限"], a:"制限"},
  {q:"「maintain」の意味は？", choices:["維持する","壊す","変える","捨てる"], a:"維持する"},
  {q:"「major」の意味は？", choices:["主要な","些細な","新しい","古い"], a:"主要な"},
  {q:"「manage」の意味は？", choices:["何とかやり遂げる","失敗する","諦める","断る"], a:"何とかやり遂げる"},
  {q:"「material」の意味は？", choices:["材料/資料","精神","結果","道具"], a:"材料/資料"},
  {q:"「measure」の意味は？", choices:["測定する","推測する","無視する","壊す"], a:"測定する"},
  {q:"「mention」の意味は？", choices:["言及する","黙る","忘れる","否定する"], a:"言及する"},
  {q:"「method」の意味は？", choices:["方法","偶然","結果","理由"], a:"方法"},
  {q:"「minimum」の意味は？", choices:["最小の","最大の","平均の","多くの"], a:"最小の"},
  {q:"「movement」の意味は？", choices:["動き","停止","沈黙","安定"], a:"動き"},
  {q:"「negative」の意味は？", choices:["否定的な","肯定的な","明るい","確実な"], a:"否定的な"},
  {q:"「nervous」の意味は？", choices:["緊張して","落ち着いて","怒って","喜んで"], a:"緊張して"},
  {q:"「notice」の意味は？", choices:["気づく","無視する","忘れる","隠す"], a:"気づく"},
  {q:"「object」の意味は？", choices:["物体/目的","精神","空気","時間"], a:"物体/目的"},
  {q:"「occasion」の意味は？", choices:["機会/行事","日常","過去","場所"], a:"機会/行事"},
  {q:"「operate」の意味は？", choices:["操作する","壊す","止まる","見る"], a:"操作する"},
  {q:"「opinion」の意味は？", choices:["意見","事実","噂","嘘"], a:"意見"},
  {q:"「ordinary」の意味は？", choices:["普通の","特別な","変な","新しい"], a:"普通の"},
  {q:"「organize」の意味は？", choices:["組織する","壊す","散らかす","待つ"], a:"組織する"},
  {q:"「original」の意味は？", choices:["独創的な/元の","コピーの","偽の","古い"], a:"独創的な/元の"},
  {q:"「particular」の意味は？", choices:["特定の","一般的な","すべての","曖昧な"], a:"特定の"},
  {q:"「passenger」の意味は？", choices:["乗客","運転手","歩行者","店員"], a:"乗客"},
  {q:"「patience」の意味は？", choices:["忍耐","怒り","速度","知能"], a:"忍耐"},
  {q:"「perfect」の意味は？", choices:["完璧な","不完全な","悪い","普通の"], a:"完璧な"},
  {q:"「performance」の意味は？", choices:["演奏/実績","練習","休憩","準備"], a:"演奏/実績"},
  {q:"「period」の意味は？", choices:["期間","瞬間","過去","未来"], a:"期間"},
  {q:"「permission」の意味は？", choices:["許可","禁止","命令","相談"], a:"許可"},
  {q:"「persuade」の意味は？", choices:["説得する","命令する","聞く","諦める"], a:"説得する"},
  {q:"「physical」の意味は？", choices:["身体的な","精神的な","知的な","架空の"], a:"身体的な"},
  {q:"「pleasant」の意味は？", choices:["楽しい/心地よい","不快な","退屈な","悲しい"], a:"楽しい/心地よい"},
  {q:"「policy」の意味は？", choices:["政策/方針","偶然","結果","噂"], a:"政策/方針"},
  {q:"「popular」の意味は？", choices:["人気のある","嫌われた","無名の","古い"], a:"人気のある"},
  {q:"「positive」の意味は？", choices:["肯定的な","否定的な","暗い","疑わしい"], a:"肯定的な"},
  {q:"「possibility」の意味は？", choices:["可能性","不可能","事実","過去"], a:"可能性"},
  {q:"「precious」の意味は？", choices:["貴重な","安い","不要な","新しい"], a:"貴重な"},
  {q:"「prepare」の意味は？", choices:["準備する","片付ける","壊す","忘れる"], a:"準備する"},
  {q:"「pressure」の意味は？", choices:["圧力","解放","平和","沈黙"], a:"圧力"},
  {q:"「prevent」の意味は？", choices:["防ぐ","促す","助ける","始める"], a:"防ぐ"},
  {q:"「previous」の意味は？", choices:["前の","次の","現在の","最後の"], a:"前の"},
  {q:"「primary」の意味は？", choices:["主要な","些細な","最後の","後の"], a:"主要な"},
  {q:"「principle」の意味は？", choices:["原理/主義","結果","偶然","物語"], a:"原理/主義"},
  {q:"「priority」の意味は？", choices:["優先事項","後回し","無視","遊び"], a:"優先事項"},
  {q:"「probably」の意味は？", choices:["おそらく","絶対に","決して","たまに"], a:"おそらく"},
  {q:"「produce」の意味は？", choices:["生産する","消費する","壊す","隠す"], a:"生産する"},
  {q:"「profit」の意味は？", choices:["利益","損失","経費","仕事"], a:"利益"},
  {q:"「progress」の意味は？", choices:["進歩","後退","停止","維持"], a:"進歩"},
  {q:"「promise」の意味は？", choices:["約束する","疑う","忘れる","嘘をつく"], a:"約束する"},
  {q:"「property」の意味は？", choices:["財産/特性","借金","損失","秘密"], a:"財産/特性"},
  {q:"「protect」の意味は？", choices:["保護する","攻撃する","壊す","捨てる"], a:"保護する"},
  {q:"「proud」の意味は？", choices:["誇りに思う","恥じる","怒る","悲しむ"], a:"誇りに思う"},
  {q:"「provide」の意味は？", choices:["提供する","奪う","隠す","拒否する"], a:"提供する"},
  {q:"「public」の意味は？", choices:["公共の","個人の","秘密の","狭い"], a:"公共の"},
  {q:"「purpose」の意味は？", choices:["目的","偶然","過去","結果"], a:"目的"},
  {q:"「quality」の意味は？", choices:["質","量","形","色"], a:"質"},
  {q:"「quantity」の意味は？", choices:["量","質","重さ","長さ"], a:"量"},
  {q:"「range」の意味は？", choices:["範囲","一点","中心","終わり"], a:"範囲"},
  {q:"「rapid」の意味は？", choices:["速い","遅い","重い","静かな"], a:"速い"},
  {q:"「reasonable」の意味は？", choices:["妥当な/手ごろな","不当な","高い","変な"], a:"妥当な/手ごろな"},
  {q:"「receive」の意味は？", choices:["受け取る","送る","捨てる","隠す"], a:"受け取る"},
  {q:"「recent」の意味は？", choices:["最近の","遠い過去の","未来の","永遠の"], a:"最近の"},
  {q:"「recognize」の意味は？", choices:["認識する","忘れる","無視する","疑う"], a:"認識する"},
  {q:"「reduce」の意味は？", choices:["減らす","増やす","維持する","変える"], a:"減らす"},
  {q:"「refer」の意味は？", choices:["言及する/参照する","無視する","書く","消す"], a:"言及する/参照する"},
  {q:"「reflect」の意味は？", choices:["反射する/反映する","吸収する","壊す","隠す"], a:"反射する/反映する"},
  {q:"「region」の意味は？", choices:["地域","世界","宇宙","一点"], a:"地域"},
  {q:"「regular」の意味は？", choices:["規則的な","不規則な","珍しい","新しい"], a:"規則的な"},
  {q:"「relationship」の意味は？", choices:["関係","孤独","敵対","無視"], a:"関係"},
  {q:"「relative」の意味は？", choices:["親戚/相対的な","他人","絶対的な","敵"], a:"親戚/相対的な"},
  {q:"「reliable」の意味は？", choices:["信頼できる","怪しい","壊れた","古い"], a:"信頼できる"},
  {q:"「relief」の意味は？", choices:["安心/除去","不安","苦痛","緊張"], a:"安心/除去"},
  {q:"「religion」の意味は？", choices:["宗教","科学","経済","政治"], a:"宗教"},
  {q:"「remain」の意味は？", choices:["ままでいる","変わる","去る","消える"], a:"ままでいる"},
  {q:"「remarkable」の意味は？", choices:["注目すべき","平凡な","些細な","古い"], a:"注目すべき"},
  {q:"「remind」の意味は？", choices:["思い出させる","忘れる","無視する","隠す"], a:"思い出させる"},
  {q:"「remote」の意味は？", choices:["遠い","近い","都会の","賑やかな"], a:"遠い"},
  {q:"「repair」の意味は？", choices:["修理する","壊す","使う","捨てる"], a:"修理する"},
  {q:"「repeat」の意味は？", choices:["繰り返す","一度だけ","止める","変える"], a:"繰り返す"},
  {q:"「replace」の意味は？", choices:["取って代わる","維持する","壊す","失う"], a:"取って代わる"},
  {q:"「reply」の意味は？", choices:["返事をする","尋ねる","無視する","去る"], a:"返事をする"},
  {q:"「report」の意味は？", choices:["報告する","隠す","聞く","忘れる"], a:"報告する"},
  {q:"「represent」の意味は？", choices:["代表する","個人で行う","隠す","壊す"], a:"代表する"},
  {q:"「request」の意味は？", choices:["要請する","命令する","断る","与える"], a:"要請する"},
  {q:"「require」の意味は？", choices:["必要とする","不要とする","与える","捨てる"], a:"必要とする"},
  {q:"「research」の意味は？", choices:["研究/調査","遊び","推測","沈黙"], a:"研究/調査"},
  {q:"「reserve」の意味は？", choices:["予約する","使う","捨てる","壊す"], a:"予約する"},
  {q:"「respect」の意味は？", choices:["尊敬する","軽蔑する","無視する","叱る"], a:"尊敬する"},
  {q:"「respond」の意味は？", choices:["反応する","無視する","眠る","待つ"], a:"反応する"},
  {q:"「responsible」の意味は？", choices:["責任がある","無責任な","自由な","軽い"], a:"責任がある"},
  {q:"「rest」の意味は？", choices:["休息/残り","運動","仕事","開始"], a:"休息/残り"},
  {q:"「result」の意味は？", choices:["結果","原因","過程","始まり"], a:"結果"},
  {q:"「reveal」の意味は？", choices:["明らかにする","隠す","壊す","忘れる"], a:"明らかにする"},
  {q:"「reward」の意味は？", choices:["報酬","罰","仕事","損失"], a:"報酬"},
  {q:"「rich」の意味は？", choices:["豊かな","貧しい","狭い","低い"], a:"豊かな"},
  {q:"「risk」の意味は？", choices:["危険","安全","保証","平和"], a:"危険"},
  {q:"「role」の意味は？", choices:["役割","本名","場所","時間"], a:"役割"},
  {q:"「rough」の意味は？", choices:["荒い/ざらざらした","滑らかな","静かな","新しい"], a:"荒い/ざらざらした"},
  {q:"「route」の意味は？", choices:["経路","目的地","出発地","迷子"], a:"経路"},
  {q:"「royal」の意味は？", choices:["王室の","民間の","個人の","安い"], a:"王室の"},
  {q:"「rule」の意味は？", choices:["規則","自由","偶然","混乱"], a:"規則"},
  {q:"「rural」の意味は？", choices:["田舎の","都会の","賑やかな","中心の"], a:"田舎の"},
  {q:"「safety」の意味は？", choices:["安全","危険","事故","不安"], a:"安全"},
  {q:"「salary」の意味は？", choices:["給料","趣味","買い物","借金"], a:"給料"},
  {q:"「sample」の意味は？", choices:["見本","本物","全体","過去"], a:"見本"},
  {q:"「satisfied」の意味は？", choices:["満足した","不満な","怒った","悲しい"], a:"満足した"},
  {q:"「save」の意味は？", choices:["救う/蓄える","捨てる","壊す","使う"], a:"救う/蓄える"},
  {q:"「scene」の意味は？", choices:["場面/景色","音","匂い","味"], a:"場面/景色"},
  {q:"「schedule」の意味は？", choices:["予定","過去","偶然","結果"], a:"予定"},
  {q:"「science」の意味は？", choices:["科学","芸術","宗教","経済"], a:"科学"},
  {q:"「score」の意味は？", choices:["得点","名前","場所","時間"], a:"得点"},
  {q:"「search」の意味は？", choices:["探す","隠す","持つ","捨てる"], a:"探す"},
  {q:"「season」の意味は？", choices:["季節","時間","時代","一生"], a:"季節"},
  {q:"「secret」の意味は？", choices:["秘密","公開","噂","ニュース"], a:"秘密"},
  {q:"「section」の意味は？", choices:["部分/区域","全体","中心","外側"], a:"部分/区域"},
  {q:"「security」の意味は？", choices:["警備/安全","危険","混乱","攻撃"], a:"警備/安全"},
  {q:"「seek」の意味は？", choices:["追い求める","避ける","捨てる","忘れる"], a:"追い求める"},
  {q:"「select」の意味は？", choices:["選ぶ","捨てる","混ぜる","壊す"], a:"選ぶ"},
  {q:"「sense」の意味は？", choices:["感覚","事実","物体","時間"], a:"感覚"},
  {q:"「sentence」の意味は？", choices:["文章/判決","単語","文字","記号"], a:"文章/判決"},
  {q:"「separate」の意味は？", choices:["分ける","つなぐ","混ぜる","壊す"], a:"分ける"},
  {q:"「serious」の意味は？", choices:["深刻な/真面目な","冗談の","軽い","陽気な"], a:"深刻な/真面目な"},
  {q:"「service」の意味は？", choices:["奉仕/役務","攻撃","無視","休憩"], a:"奉仕/役務"},
  {q:"「set」の意味は？", choices:["置く/決める","動かす","壊す","探す"], a:"置く/決める"},
  {q:"「settle」の意味は？", choices:["解決する/定住する","混乱させる","去る","壊す"], a:"解決する/定住する"},
  {q:"「several」の意味は？", choices:["いくつかの","一つの","たくさんの","すべての"], a:"いくつかの"},
  {q:"「shape」の意味は？", choices:["形","色","重さ","味"], a:"形"},
  {q:"「share」の意味は？", choices:["共有する","独占する","捨てる","隠す"], a:"共有する"},
  {q:"「sharp」の意味は？", choices:["鋭い","鈍い","丸い","柔らかい"], a:"鋭い"},
  {q:"「shift」の意味は？", choices:["移る/交代","止まる","壊す","維持する"], a:"移る/交代"},
  {q:"「shock」の意味は？", choices:["衝撃","安定","平和","日常"], a:"衝撃"},
  {q:"「sight」の意味は？", choices:["視力/光景","聴覚","味覚","触覚"], a:"視力/光景"},
  {q:"「signal」の意味は？", choices:["信号","沈黙","事実","噂"], a:"信号"},
  {q:"「significant」の意味は？", choices:["重要な","些細な","新しい","古い"], a:"重要な"},
  {q:"「similar」の意味は？", choices:["似ている","異なる","反対の","全く同じ"], a:"似ている"},
  {q:"「simple」の意味は？", choices:["単純な","複雑な","難しい","高い"], a:"単純な"},
  {q:"「since」の意味は？", choices:["〜以来","〜まで","〜の間","〜の後で"], a:"〜以来"},
  {q:"「situation」の意味は？", choices:["状況","原因","結果","目的"], a:"状況"},
  {q:"「skill」の意味は？", choices:["技能","才能","運","外見"], a:"技能"},
  {q:"「social」の意味は？", choices:["社会的な","個人的な","秘密の","野生の"], a:"社会的な"},
  {q:"「solution」の意味は？", choices:["解決策","問題","原因","過程"], a:"解決策"},
  {q:"「source」の意味は？", choices:["源/情報源","結果","出口","終わり"], a:"源/情報源"},
  {q:"「space」の意味は？", choices:["空間/宇宙","時間","物体","重さ"], a:"空間/宇宙"},
  {q:"「specific」の意味は？", choices:["特定の","曖昧な","一般的な","すべての"], a:"特定の"},
  {q:"「speech」の意味は？", choices:["演説","沈黙","筆記","読書"], a:"演説"},
  {q:"「spend」の意味は？", choices:["費やす","貯める","稼ぐ","捨てる"], a:"費やす"},
  {q:"「spirit」の意味は？", choices:["精神","肉体","物体","機械"], a:"精神"},
  {q:"「standard」の意味は？", choices:["標準","例外","偶然","混乱"], a:"標準"},
  {q:"「stare」の意味は？", choices:["じっと見る","目をそらす","閉じる","眠る"], a:"じっと見る"},
  {q:"「state」の意味は？", choices:["状態/州/述べる","隠す","壊す","聞く"], a:"状態/州/述べる"},
  {q:"「structure」の意味は？", choices:["構造","混沌","一部分","材料"], a:"構造"},
  {q:"「subject」の意味は？", choices:["主題/科目","答え","終わり","余白"], a:"主題/科目"},
  {q:"「succeed」の意味は？", choices:["成功する","失敗する","諦める","断る"], a:"成功する"},
  {q:"「support」の意味は？", choices:["支持する","反対する","攻撃する","無視する"], a:"支持する"},
  {q:"「surface」の意味は？", choices:["表面","内部","中心","底"], a:"表面"},
  {q:"「survive」の意味は？", choices:["生き残る","死ぬ","去る","眠る"], a:"生き残る"},
  {q:"「system」の意味は？", choices:["体系/仕組み","偶然","混乱","一部分"], a:"体系/仕組み"},
  {q:"「target」の意味は？", choices:["標的","過去","偶然","余白"], a:"標的"},
  {q:"「task」の意味は？", choices:["任務/仕事","遊び","休憩","趣味"], a:"任務/仕事"},
  {q:"「tax」の意味は？", choices:["税金","給料","贈り物","利益"], a:"税金"},
  {q:"「technical」の意味は？", choices:["技術的な","芸術的な","自然の","精神的な"], a:"技術的な"},
  {q:"「temperature」の意味は？", choices:["温度","重さ","長さ","速さ"], a:"温度"},
  {q:"「temporary」の意味は？", choices:["一時的な","永遠の","日常の","古い"], a:"一時的な"},
  {q:"「term」の意味は？", choices:["用語/期間","瞬間","数字","場所"], a:"用語/期間"},
  {q:"「theory」の意味は？", choices:["理論","事実","実践","噂"], a:"理論"},
  {q:"「though」の意味は？", choices:["〜だけれども","〜なので","〜の後に","〜の前に"], a:"〜だけれども"},
  {q:"「threat」の意味は？", choices:["脅威","安全","平和","助け"], a:"脅威"},
  {q:"「through」の意味は？", choices:["〜を通して","〜の隣に","〜の下に","〜の上に"], a:"〜を通して"},
  {q:"「tight」の意味は？", choices:["きつい","ゆるい","広い","遠い"], a:"きつい"},
  {q:"「total」の意味は？", choices:["合計の","一部の","空の","新しい"], a:"合計の"},
  {q:"「tough」の意味は？", choices:["たくましい/困難な","弱い","簡単な","柔らかい"], a:"たくましい/困難な"},
  {q:"「traditional」の意味は？", choices:["伝統的な","最新の","個人的な","珍しい"], a:"伝統的な"},
  {q:"「traffic」の意味は？", choices:["交通","通信","静寂","孤独"], a:"交通"},
  {q:"「transfer」の意味は？", choices:["移す","維持する","壊す","止める"], a:"移す"},
  {q:"「treasure」の意味は？", choices:["宝物","ゴミ","借金","損失"], a:"宝物"},
  {q:"「trend」の意味は？", choices:["傾向","伝統","過去","停止"], a:"傾向"},
  {q:"「trust」の意味は？", choices:["信頼する","疑う","無視する","恐れる"], a:"信頼する"},
  {q:"「unique」の意味は？", choices:["独特の","普通の","共通の","古い"], a:"独特の"},
  {q:"「unit」の意味は？", choices:["単位","全体","宇宙","偶然"], a:"単位"},
  {q:"「urgent」の意味は？", choices:["緊急の","のんびりした","過去の","不要な"], a:"緊急の"},
  {q:"「value」の意味は？", choices:["価値","値段","重さ","量"], a:"価値"},
  {q:"「variety」の意味は？", choices:["多様性","単一","同じ","終わり"], a:"多様性"},
  {q:"「various」の意味は？", choices:["様々な","一つの","同じ","少しの"], a:"様々な"},
  {q:"「vehicle」の意味は？", choices:["乗り物","建物","食べ物","道具"], a:"乗り物"},
  {q:"「view」の意味は？", choices:["眺め/考え","音","匂い","味"], a:"眺め/考え"},
  {q:"「vision」の意味は？", choices:["視覚/展望","聴覚","過去","沈黙"], a:"視覚/展望"},
  {q:"「voice」の意味は？", choices:["声","沈黙","筆記","外見"], a:"声"},
  {q:"「volume」の意味は？", choices:["音量/巻","色","形","味"], a:"音量/巻"},
  {q:"「waste」の意味は？", choices:["浪費する/ゴミ","節約する","作る","育てる"], a:"浪費する/ゴミ"},
  {q:"「weapon」の意味は？", choices:["武器","防具","道具","おもちゃ"], a:"武器"},
  {q:"「weather」の意味は？", choices:["天気","季節","時間","時代"], a:"天気"},
  {q:"「weight」の意味は？", choices:["重さ","長さ","速さ","温度"], a:"重さ"},
  {q:"「whole」の意味は？", choices:["全体の","一部の","空の","新しい"], a:"全体の"},
  {q:"「wide」の意味は？", choices:["広い","狭い","高い","低い"], a:"広い"},
  {q:"「willing」の意味は？", choices:["いとわない","嫌がる","無理に","決して"], a:"いとわない"},
  {q:"「worth」の意味は？", choices:["価値がある","安い","不要な","古い"], a:"価値がある"},
  {q:"「wrap」の意味は？", choices:["包む","広げる","壊す","捨てる"], a:"包む"},
  {q:"「youth」の意味は？", choices:["若さ","老い","過去","未来"], a:"若さ"}
];
